### ISSUE TITLE
Server error on profile image upload

### ISSUE THREAD

**Issue by joops** [meanjs/mean#740] opened 2015-07-31 10:52 UTC
I'm seeing a mongoose error when calling api/users/picture from the client side with the latest version of 0.4.0. This occurs when hitting the upload button from change-profile-picture.client.view upload view.

It looks like the call is passing a value of 'picture' from the url path to the userByID middleware, which is being interpreted as 'id', thereby causing a cast error. I've confirmed this as the problem - remove the middleware and the image uploads as expected.

Does anybody else see this behaviour? I'm trying to find a fix and will post back if I come up with anything.

**Comment by mleanos** [comment] 2015-07-31 12:36
You identified the issue correctly. The issue is with the 'picture' part of the route, getting mistaken for the `:userId` implemented in the Admin route `/api/users/:userId`. You should see this in the in the `admin.server.routes` file. 

This was fixed in the 0.4.0 branch, and released just a couple of days ago. Can you verify that the version your running is aligned with PR #713?

**Comment by codydaig** [comment] 2015-07-31 17:06
@joops @mleanos This has been fixed in the latest branch of 0.4.0 by #713. I just tested this.

**Comment by lirantal** [comment] 2015-07-31 17:35
thanks @codydaig

**Closed by lirantal** 2015-07-31 17:35 UTC
Labels: bug

**Comment by joops** [comment] 2015-08-01 00:42
Much appreciated @mleanos @codydaig @lirantal -- ironically I merged to 0.4.0 the day before this fix went in, but didn't see the update when looking yesterday. All good now, thanks a million for the help!

**Comment by codydaig** [comment] 2015-08-01 01:27
@joops Glad to hear it was a simple fix!
