### ISSUE TITLE
google authentication callback url bug

### ISSUE THREAD

**Issue by junit38** [meanjs/mean#535] opened 2015-04-27 17:50 UTC
Hi,
I get URL like localhost:3000/# when I use google authentication with passport.

I fixed the problem using the same way which has been used to fix the Facebook bug with redirect (public/modules/application.js):

```
//Then define the init function for starting up the application
angular.element(document).ready(function() {
	// Fixing facebook bug with redirect
	if (window.location.hash === '#_=_') window.location.hash = '#!';

	// Then init the app
	angular.bootstrap(document, [ApplicationConfiguration.applicationModuleName]);
});
```

I added this part:

```
// Fixing google bug with redirect
	if (window.location.href[window.location.href.length - 1] === '#' &&
		// for just the error url (origin + /#)
		(window.location.href.length - window.location.origin.length) === 2) {
		window.location.href = window.location.origin + '/#!';
	}
```

Does you know something about it?

Thanks.

**Comment by ilanbiala** [comment] 2015-04-27 22:52
Are you missing some code there? Maybe an if and another closing brace?

**Comment by junit38** [comment] 2015-04-28 11:17
I added this code into the first function, the whole become:

```
//Then define the init function for starting up the application
angular.element(document).ready(function() {
	// Fixing facebook bug with redirect
	if (window.location.hash === '#_=_') window.location.hash = '#!';

	// Fixing google bug with redirect
	if (window.location.href[window.location.href.length - 1] === '#' &&
		// for just the error url (origin + /#)
		(window.location.href.length - window.location.origin.length) === 2) {
		window.location.href = window.location.origin + '/#!';
	}

	// Then init the app
	angular.bootstrap(document, [ApplicationConfiguration.applicationModuleName]);
});
```

**Comment by ppotoplyak** [comment] 2015-04-30 02:33
ditto, started hitting the same issue recently.

Here is the workaround that I am running with:

```
// Then define the init function for starting up the application
angular.element(document).ready(function() {
  if (window.location.hash === '#_=_') {
    //Fixing facebook bug with redirect
    window.location.hash = '#!';
  } else if(window.location.hash.length === 0) {
    // Without this, after G+ auth we started taking:
    // Uncaught Error: [$location:ihshprfx] Invalid url "https://streetspin.com/#", missing hash prefix "#!"
    // needs to be root caused at some point
    window.location.hash = '#!/';
  }

  //Then init the app
  angular.bootstrap(document, [ApplicationConfiguration.applicationModuleName]);
});
```

I was not sure if this was a self imposed regression or something outside of our control.

**Comment by ppotoplyak** [comment] 2015-04-30 03:18
Just checked tip and the issue is still there but it seems browser dependent.

No problems using Firefox:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0

Issue is there with Chrome:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36

Chrome taking this error:
angular.js:78 Uncaught Error: [$location:ihshprfx] Invalid url "http://localhost:3000/#", missing hash prefix "#!".
http://errors.angularjs.org/1.2.28/$location/ihshprfx?p0=http%3A%2F%2Flocalhost%3A3000%2F%23&p1=%23!

**Comment by ppotoplyak** [comment] 2015-05-04 03:41
Wiresharking reveals that indeed a # is being appended to the callback URL but only when using Chrome.

This should probably be bumped up to a P1 priority as Chrome G+ auth is not functioning properly without a workaround.  junit38's workaround is probably the more elegant as it specifically addresses this issue.

@junit38 , let me know if you would like to submit a PR, otherwise I can put one together.

The real question is why is Google appending the # with no error code to follow, please upvote if you agree:
http://stackoverflow.com/questions/30010046/added-to-google-oauth-2-0-callback-url/

thanks

**Comment by junit38** [comment] 2015-05-05 14:59
@ppotoplyak I'm ok to submit a PR let me know how to proceed and when I can do it.

Thanks

**Comment by ppotoplyak** [comment] 2015-05-05 15:18
@junit38 lets get guidance from ilanbiala as he would be the approving authority.

@ilanbiala we would like to make sure that you agree that this is a real issue and a PR for a workaround is required?

thanks

**Comment by floydpink** [comment] 2015-05-20 03:29
Thank you @junit38 and @ppotoplyak - have submitted a PR with the fix from @junit38

**Closed** 2015-07-29 13:57 UTC
