### ISSUE TITLE
How to auto redirect http to https (while secure mode is enabled)?

### ISSUE THREAD

**Issue by nirber** [meanjs/mean#888] opened 2015-09-05 23:16 UTC

**Comment by igorauad** [comment] 2015-09-05 23:18
Perhaps this is useful for you (to include in `express.js`):

```{js}
// Force https in production
  if (process.env.NODE_ENV === 'production') {
    app.use(function(req, res, next) {
        if (req.headers['x-forwarded-proto'] !== 'https') {
            return res.redirect(['https://', req.get('Host'), req.url].join(''));
        }
        return next();
    });
  }
```

**Comment by nirber** [comment] 2015-09-05 23:25
Thanks Igor,

Tried something like that before and your exact code now, but it's not working.

Any ideas?

**Comment by igorauad** [comment] 2015-09-05 23:27
Hard to tell. Is that a problem with your certificate? 

I use it within `module.exports.initMiddleware = function (app) {`

**Comment by codydaig** [comment] 2015-09-05 23:28
@nirber If you're having specific issues with your code, please provide a link to your code or paste the section of code into a code block here to better assist you in your debugging. It's hard to help debug blindly.

**Comment by nirber** [comment] 2015-09-05 23:34
You're right!

module.exports.initMiddleware = function (app) {
	
	app.use (function (req, res, next) {
    	if (req.protocol === 'https') {
			console.log(req.protocol, req.secure);
            next();
        } else {
		  	console.log('redirected');
            res.redirect('https://' + req.headers.host + req.url);
        }
  	});
...

When I use https everything works great. When not, nothing is loaded.

**Comment by igorauad** [comment] 2015-09-05 23:36
Yes! Good that it worked.

**Comment by nirber** [comment] 2015-09-05 23:37
It didn't worked. In secure mode, if I'm using 'http://...' , nothing is getting loaded

**Comment by codydaig** [comment] 2015-09-05 23:45
@nirber Is 'redirected' printing in the console at all?

**Comment by nirber** [comment] 2015-09-05 23:47
no

**Comment by codydaig** [comment] 2015-09-06 00:16
@nirber Is anything getting logged from either of those conditional statements?

**Comment by nirber** [comment] 2015-09-06 00:21
If I use https://.. the if statement is being valuated true and there is logging to the console. If I use http, nothing is logged.

I kept investigating and I think it is because the server is not listening on the 80 port, so the 'http://..' request is not going through the middleware(s).

**Comment by codydaig** [comment] 2015-09-06 21:15
@nirber Have you tried @igorauad's solution using req.headers?

**Comment by nirber** [comment] 2015-09-06 21:35
@codydaig Yes, but the middleware isn't getting executed at all if I go to a non 'https' url.

**Comment by nirber** [comment] 2015-09-07 00:03
Just tried to revert back to ssl > 'false' and it is working well with the redirection.
Is it safe this way?

**Comment by codydaig** [comment] 2015-09-07 03:54
@nirber I personally don't like using < or > operators against booleans. Just do a check and if ssl !== false then do the redirection. I don't see any issues with either way though.

**Comment by lirantal** [comment] 2015-09-07 05:14
@nirber redirection is usually a function of the SSL terminator, your load balancer, or some other network equipment on the Internet leg.
I wouldn't try to push this kind of logic into your web application. It's just as if you wouldn't want to start putting firewall rules into your nodejs app to decide who can access your app.

**Comment by nirber** [comment] 2015-09-07 10:08
Thanks guys, I will enforce https on the load-balancer.

**Comment by mikepc** [comment] 2015-09-10 00:57
That isn't acceptable, for heroku  dynos they are hosting the traffic directly, with no reverse proxy in front of it. This needs to work.

**Comment by lirantal** [comment] 2015-09-10 06:54
Great, closing.

**Closed by lirantal** 2015-09-10 06:54 UTC
Labels: question

**Comment by mikepc** [comment] 2015-09-11 14:04
Ok Just so we're clear, you're closing a Bug that is unfixed and will potentially have pretty severe blowback. Clone the repo, enable ssl locally and http://localhost:3000, you will have to control-c to restart the server.

Once you enable SSL, when run locally, when you http:// into a local instance the server thread is hung, and must be restarted. There is no error. There is no way to redirect the request to https:// so you essentially can't ssl locally. 

I can ssl using the heroku remote, but none of my middleware is actually working to redirect to https from http, so I'm trying to figure out a workaround. Since I can't http locally it makes testing my redirect middleware horrendous.

I know that this dude moved the redirect to the rproxy, but dude on heroku we have no rproxy, node's hangin' out there with junk in the wind, which means if I don't ssl with node, I either dump heroku and my whole deployment plan or I find some hack to get ssl to work.

Any help getting this resolved would be very appreciated.

**Comment by simison** [comment] 2015-09-11 14:48
@mikepc As a hack, can you run another minimum server at port 80 and 301-redirect from there?

**Comment by mikepc** [comment] 2015-09-11 15:31
A helpful guy from the meanjs google group sent me some tips, he found that the problem is in socket.io and says that he has it working:


in socket.io

remove 

} else { 

and provide different names for the servers


var h = http.createServer(options, app);
var hs = https.createServer(app);

Listen only to https on socket.io (if you use or need it)

var io = socketio.listen(hs);

Then at the end return both servers

return {
	http: h,
	https: hs
};

then in server.js

I'm able to 

app.http.listen(config.port);
app.https.listen(config.https.port);

Up to you if you want to print out the stuff in the function () on server starts.


That way it starts both servers and you can redirect the http traffic to https.



Then insert in express.js:

app.use(function(req, res, next) {
    if(!req.secure) {
        return res.redirect('https://' + req.get('Host') + req.url);
    }
    next();
});


In addition, if you do not run the https server on port 443 need to modify the app.use

Haven't run it this way but you will have to insert the port the https is listening on

Untested need to debug if you need the / or not

app.use(function(req, res, next) {
    if(!req.secure) {
        return res.redirect('https://' + req.get('Host') + ':' + config.https.port + '/' + req.url);
    }
    next();
});

At work now but will be hooking this up when I get home later this evening

**Comment by jloveland** [comment] 2015-09-15 00:46
@mikepc are you making a pull request for this? I think it would be valuable.

**Comment by mleanos** [comment] 2015-09-15 00:58
:+1: I'd like to see a PR for this as well.

**Comment by lirantal** [comment] 2015-09-15 15:44
why PR for this? I thought we were ok with handling this on the network devices level (Firewall / LB / etc)

**Comment by jloveland** [comment] 2015-09-16 03:14
it would be nice to have it as an option to have node redirect without something like nginx in front. I can see how it adds some complexity, but if it's configurable it may be worth it.

**Comment by ilanbiala** [comment] 2015-09-16 03:57
@jloveland if something is better done something else I'm not in support of adding it to bloat the framework just for the convenience for small cases.

**Comment by mleanos** [comment] 2015-09-16 04:22
I agree with @ilanbiala 

I was just more curious than anything, to explore what a seamless, unintrusive, and configurable solution might look like for this.

**Comment by lirantal** [comment] 2015-09-16 04:55
exactly as @ilanbiala , because we *can*, it doesn't mean we *should.

**Comment by jloveland** [comment] 2015-09-17 00:08
sounds good to me then! I was curios as @mleanos was...but having the load balancer or ssl terminator do this makes sense to me in a production env.

**Comment by lirantal** [comment] 2015-09-18 07:17
:+1:
