### ISSUE TITLE
User passwords keep changing

### ISSUE THREAD

**Issue by JoaoPintoM** [meanjs/mean#295] opened 2014-12-08 19:43 UTC
Hello,

I'm playing with meanjs 0.3 and I have to recreate new users because the passwords seems to change all the time.. Sometimes it works sometimes not and works again.. I have no idea what is happening.

Thx in advance if you have any idea about that issue.

Joao

**Comment by smirnovigor** [comment] 2015-01-05 21:29
@yesnault Thank you, it's helped me.

**Comment by ilanbiala** [comment] 2015-01-08 00:34
@smirnovigor @yesnault does #253 cover the same thing that you guys are talking about?

**Comment by smirnovigor** [comment] 2015-01-14 20:35
@ilanbiala No, this issue happens on update user with already encrypted password field. Then encrypted password pass again through pre-save model cycle and encrypt encrypted password.

**Comment by ilanbiala** [comment] 2015-01-14 21:04
@smirnovigor the issue seems like the if-else has to be reversed in [this method](https://github.com/meanjs/mean/blob/master/app/models/user.server.model.js#L109), right?

**Comment by smirnovigor** [comment] 2015-01-14 21:35
No, it's more complicated. You shouldn't re-encrypt password and salt on every save. Take a look to the @yesnault [commit](https://github.com/docktor/docktor/commit/1f00332b4dfbdd8de992c8cd94156676171e869e)

**Comment by ilanbiala** [comment] 2015-01-14 21:45
@smirnovigor I think it makes more sense to check before saving the document instead of deciding when to check.

The issue is actually that we keep generating a new password because we are using a new salt. Also, it's not really clear to me why we are passing in a password that may have already been hashed (in the case of an update to the document).

@lirantal maybe you can clear up some of these questions?

**Comment by lirantal** [comment] 2015-01-15 09:34
I've no idea what password re-encryption is being discussed here.
@smirnovigor :
1. can you provide the steps to reproduce the problem? I saved the user profile and the password isn't changing.
2. that commit you referred to is out of the date from meanjs perspective as the changes there are not reflecting the current state of meanjs 'master' branch.

**Comment by ilanbiala** [comment] 2015-01-15 16:02
@lirantal it's because we do a save on the `_.extend`ed User document that the pre save middleware gets called and the password will be re-hashed it seems.

**Comment by lirantal** [comment] 2015-01-15 16:04
@ilanbiala tell me how to reproduce it?

**Comment by ilanbiala** [comment] 2015-01-15 16:05
If the pre save middleware really is kicking in, I think you just have to update a user and change anything but the password. Keep track of the password before and after.

**Comment by lirantal** [comment] 2015-01-16 09:56
@ilanbiala read my reply to smirnovigor from yesterday - I tried that and couldn't reproduce the problem. Unless someone can reproduce it I'm closing.

**Comment by dk253** [comment] 2015-03-12 20:27
Not sure if anyone is listening here anymore... but I ran into the same issue.  Fixed it with a hack in the UserSchema.pre function.  Not perfect, but works for now.  
Changed the if statement to read:
if (this.password && this.password.length > 6 && this.password.length < 60) {

**Comment by lirantal** [comment] 2015-03-19 06:41
@dk253 if we're unable to reproduce the problem we won't be able to fix it.
can you explain exactly how is it reproducing for you?

**Comment by Dollab** [comment] 2015-03-19 08:18
The 'pre' middleware in the user model is hashing the password every time the user is saved. It is not a problem when the password field must be re-posted y the user to enable modification of the user object (as in the mean.js boilerplate) but if it is not the case the password field  is taken from the db via _extend in the update method and is already hashed. To prevent this, the hash method should not be in a 'pre' middleware but defined as a separate method which is only called when needed.

**Comment by lirantal** [comment] 2015-03-19 11:51
@Dollab thanks for explaining. Is there a clear way to reproduce this problem on the mean.js boilerplate?

**Comment by dk253** [comment] 2015-03-19 12:08
Ooops... sorry I missed your request.  I agree with Dollab.  I have not tried to reproduce on the boilerplate.  But I can tell you that when the user saves their profile it does not hash the password.  But when I saved the user object it did.  Not sure if this novice explanation helps or not.

**Comment by lirantal** [comment] 2015-04-13 17:44
Ok, re-opening for when we're able to fix this with the 0.4 branch

**Comment by julienbachmann** [comment] 2015-06-09 15:51
I think you can fix it just by modifying the pre save function like this:
```javascript
UserSchema.pre('save', function(next) {
	if (this.password && this.isModified('password') && this.password.length > 6) {
		this.salt = crypto.randomBytes(16).toString('base64');
		this.password = this.hashPassword(this.password);
	}

	next();
});
```

In fact we re hash the password only if it is modified (so if password field contains a clear password).

**Comment by loulin** [comment] 2015-06-18 14:50
prefer yesnault's [commit](https://github.com/docktor/docktor/commit/1f00332b4dfbdd8de992c8cd94156676171e869e), is there any other solution? or @yesnault can commit to 0.4.0

**Comment by julienbachmann** [comment] 2015-06-18 15:25
Yes, his solution is better in term of performance as it remove the pre save hook.

But you need to be careful that you won't forget to call the method preparePassword  everywhere you set password to a user. Because if a developer add code to set password of user somewhere else in the code, then it will be stored in clear in the DB and also user won't be able to log in again.

So I think the better solution would be to redefine the setter of password field so that it won't be possible to store a clear password in the user model.

```javascript
	password: {
		type: String,
		default: '',
		validate: [validateLocalStrategyPassword, 'Password should be longer'],
		set: hashPassword
	},

...

function hashPassword(clearPwd) {
	if (clearPwd && clearPwd.length > 6) {
		this.salt = crypto.randomBytes(16).toString('base64');
		return this.hashPassword(clearPwd);
	}
	return '';
}
```

**Comment by loulin** [comment] 2015-06-19 04:23
Good idea. I tested your changes and it worked fine.
I removed the password length check because its validation function is enough.
See copy from @julienbachmann [fork commit](https://github.com/loulin/mean/commit/f3687a4d7c3e0d3621024e737d1ccc961f329eea)

**Comment by julienbachmann** [comment] 2015-06-19 07:28
In fact as you hash pwd in setter, validation will be performed on hashed password, so your validation won't work as expected. By checking pwd in setter, you will raise validation as pwd will be empty.

You should also add a test that validate pwd setting works as expected. I don't have time right now otherwise I would have fork and propose a pull request.

**Comment by lirantal** [comment] 2015-06-29 07:30
@julienbachmann or @loulin would you like to create a PR vs 0.4 branch with @julienbachmann's proposed solution? please add/modify tests as required so we can be sure everything is working as expected.

**Comment by lirantal** [comment] 2015-07-11 09:26
no worries, I've created a PR to address this issue: https://github.com/meanjs/mean/pull/642 and also added tests for the problem

**Closed** 2015-07-11 09:26 UTC
Labels: PRs please, question
