### ISSUE TITLE
Redirecting back to root

### ISSUE THREAD

**Issue by ChrisMaher** [meanjs/mean#1178] opened 2016-01-31 23:56 UTC
There seems to be a redirect back to root at the top of the Authentication.Client.Controller

```
// If user is signed in then redirect back home
    if ($scope.authentication.user) {
      $location.path('/');
    }
```

Seems to cause a lot of problems when i try implement a comment system on a module such as articles for example. When someone posts a comment on the article it redirects them away from the page and back to root. If i refresh the article.view page it also redirects the user back to root.

What is the benefit of having this redirect in MEAN.js?

**Comment by trendzetter** [comment] 2016-02-01 21:44
probably something wrong with the url of your button you use to submit. Are you using the ui-router properly?

**Comment by ChrisMaher** [comment] 2016-02-01 23:53
It happens when i refresh the page with no submit button involved. 

What it seems to do is as soon as it calls the Authentication controller, check if the user is logged in. if they are then it redirects back to root.

Just happened to notice it when making this comments system.

I suppose the question is in on a fresh install of MEANJS does it redirect back to root if you refresh the article module.view page? If not i need to find out what i changed to make it redirect.

**Comment by mleanos** [comment] 2016-02-02 09:28
@ChrisMaher Refreshing the Article view does not redirect baxk to root, on the latest master branch. I can confirm that. 

The Authentication controller shouldn't be involved when interacting with the Articles modules. The Auth controller should only be accessed if the User isn't logged in. Gotta be sonething that was mistakingly put in place in your app.

**Comment by trendzetter** [comment] 2016-02-02 21:40
Same here. Refreshing causes no issues with me.

**Comment by mleanos** [comment] 2016-02-29 04:22
Closing, since the behavior could not be reproduced.

@ChrisMaher Feel free to re-open if you're still seeing this issue with a fresh clone.

**Closed by mleanos** 2016-02-29 04:22 UTC
Labels: question
