### ISSUE TITLE
Auth doesn't work on fresh install

### ISSUE THREAD

**Issue by davidsielert** [meanjs/mean#341] opened 2015-01-02 00:08 UTC
Can't signup/signin .. 

```
Page Not Found

	/auth/signup is not a valid path.


GET /auth/signup 404 4.642 ms - -
````

**Comment by lirantal** [comment] 2015-01-02 11:23
You're right, that's exactly the same thing I noticed and opened https://github.com/meanjs/mean/issues/334 and then closed it because I thought it worked on FF fine, but I am now able to reproduce the problem on both FF, and Chrome and it's definitely not a cache issue.

@NeverOddOrEven @ilanbiala @roieki  can you take a look?
It's definitely a critical issue - what seems to happen is that the sign-in/sign-up pages show up, but once you sign-in with the user the top navigation bar doesn't change and the user thinks he isn't logged in.

**Comment by ilanbiala** [comment] 2015-01-02 15:02
What user code changes have been made recently? Any PRs/commits made before this issue started coming up, or is this something we are discovering just now?

**Comment by davidsielert** [comment] 2015-01-02 18:51
it gets a 404 to /auth/signup on my end

**Comment by lirantal** [comment] 2015-01-02 19:15
because there's no GET route for the signup or signin pages, they are being provided by AngularJS side. If you go to /auth/signout and then again to /auth/signin it should work, let me know please.

**Comment by lirantal** [comment] 2015-01-06 21:12
@davidsielert my comment on this, as I may have tracked the issue down:
There seems to have been an angular update that we needed to install. Running 'npm install' installed it for me, and fixed the authentication issue.

Can you try it too and let me know if it's resolved?

**Comment by davidsielert** [comment] 2015-01-06 22:01
I appreciate the fast action but due to the issue I just rolled my own mean stack, Sorry! I could I guess try to download it again and see if it works now though if it would help you..

**Comment by lirantal** [comment] 2015-01-06 22:02
Nah, it's ok. Thanks for replying back promptly.

**Closed by lirantal** 2015-01-06 22:02 UTC
