### ISSUE TITLE
0.4.0 and master roadmap

### ISSUE THREAD

**Issue by dotch** [meanjs/mean#455] opened 2015-03-06 23:33 UTC
I was trying to find some info on what's keeping 0.4.0 from being merged into master since I was a little bit worried about those 2 branches diverging.
all I could find was a suggestion to do a hangout in  #344
are there any updates on this?

**Comment by ilanbiala** [comment] 2015-03-06 23:54
Dupe of https://github.com/meanjs/mean/issues/402. Please search for other issues before posting a new one next time.

**Closed by ilanbiala** 2015-03-06 23:54 UTC

**Comment by dotch** [comment] 2015-03-06 23:57
sorry! missed that one!
