### ISSUE TITLE
Menu dropdowns causing NPE 

### ISSUE THREAD

**Issue by britztopher** [meanjs/mean#365] opened 2015-01-15 13:34 UTC
I think this might be a bug with the version of angular bootstrap (currently 11.2.0), but when I click on a sub menu in articles (the example article) I get this error

` Uncaught TypeError: Cannot read property 'getToggleElement' of null`

Actually the errror is linked in ui-boostrap's issues here:
[Issue 2343](https://github.com/angular-ui/bootstrap/issues/2343)

And they said its fixed in 0.12.0, however, when I try to update ui-bootstrap to version 12 they dropdowns no longer work.

**Comment by ilanbiala** [comment] 2015-01-15 16:04
This should fix it in 0.12.0.

https://github.com/angular-ui/bootstrap/issues/3094

**Comment by britztopher** [comment] 2015-01-15 16:57
@ilanbiala So the question is can we update ui-bootstrap, angular, and bootstrap to latest versions, so as to remove this 11.2 dependency which is causing this NPE?  That upgrade seems like a meanjs specific issue because the bower.json has 11.2 listed as it's angular-bootstrap dependency.

**Comment by ilanbiala** [comment] 2015-01-15 17:14
@britztopher does the link I provided fix the issue when upgrading to 0.12?

**Comment by britztopher** [comment] 2015-01-15 17:27
@ilanbiala Yes it does, thanks for that.  So it seems that the bower.json file on github has 2 dependencies for angular-bootstrap (11.2 and 12).  Also, the yo generator seems to be whats broken here because when I used it I got the NPE, however, when I forked this repo it was fixed.  Just FYI.  BTW, thanks for the info @ilanbiala

**Comment by ilanbiala** [comment] 2015-01-15 17:34
@britztopher Can you create a PR with the fixes and I'll help get it merged in so others don't have this issue.

**Comment by britztopher** [comment] 2015-01-15 17:56
@ilanbiala Like I said its fixed on this github repo, however, when you use the generator it must have an incorrect branch/tag name for repo.  I dont really know how to specify this github repo and this branch/tag name in a yo generator.  If you can show me where I will be more than happy to fork then do PR.

**Comment by ilanbiala** [comment] 2015-01-15 19:10
@britztopher are you using the master branch or the 0.4 branch?

**Comment by britztopher** [comment] 2015-01-15 19:14
@ilanbiala I am using master for both this and generator repo

**Comment by ilanbiala** [comment] 2015-01-15 19:22
The issue is that generator-meanjs is actually not using code from this repo, so when anything here gets updated, it has to manually get updated there, and it probably didn't. @NeverOddOrEven since you are handling the generator development, any ideas on what we can do here?

**Comment by ilanbiala** [comment] 2015-03-27 14:51
@britztopher, because we are looking at angular-material and also upgrading AngularJS, we'll need to wait for ui-bootstrap to catch up and support >=1.3. For now, I'm going to put this in the backlog for issues we'll look at at a later time.

**Comment by britztopher** [comment] 2015-03-27 15:12
@ilanbiala  ok, btw, i am using 0.4.0 with 1.3.x and it's working now fine, so I am guessing whenever you guys merge in 0.4.0 into master this ticket can be closed

**Comment by codydaig** [comment] 2015-07-23 19:49
Since this is taken care of in 0.4.0, can this be closed?

**Comment by lirantal** [comment] 2015-07-24 18:28
Yes, closing.

**Closed by lirantal** 2015-07-24 18:28 UTC
Labels: Not Mean.JS Specific, question

**Comment by vipul-jain** [comment] 2016-03-11 05:36
What does NPE stands for ?

**Comment by lirantal** [comment] 2016-03-11 12:07
https://en.wikibooks.org/wiki/Java_Programming/Preventing_NullPointerException
