### ISSUE TITLE
0.4 - favicon link in layout.server.view.html

### ISSUE THREAD

**Issue by mg1075** [meanjs/mean#608] opened 2015-06-29 16:23 UTC
I believe the link for the favicon needs to be changed in the core module, because the link is missing a reference to the client folder.

current: 
`<link href="/modules/core/img/brand/favicon.ico" rel="shortcut icon" type="image/x-icon">`

change to:
`<link href="/modules/core/client/img/brand/favicon.ico" rel="shortcut icon" type="image/x-icon">`

**Comment by mg1075** [comment] 2015-06-29 17:57
I guess the question really is: why should config/lib/express.js be taking out '/client'? What is the rationale for this?

```
/**
 * Configure the modules static routes
 */
module.exports.initModulesClientRoutes = function (app) {
	// Setting the app router and static folder
	app.use('/', express.static(path.resolve('./public')));

	// Globbing static routing
	config.folders.client.forEach(function (staticPath) {
		app.use(staticPath.replace('/client', ''), express.static(path.resolve('./' + staticPath)));
	});
};
```

**Comment by lirantal** [comment] 2015-06-30 21:16
@mg1075 I'm not sure why is that.
What's else in /client? can you investigate and shed more light there?

**Comment by pgrodrigues** [comment] 2015-07-01 11:02
0.4.0 is using `serve-favicon` middleware in `config/lib/expressjs` which indeed has the correct path to the favicon:

    // Initialize favicon middleware
    app.use(favicon('./modules/core/client/img/brand/favicon.ico'));

and will intercept any `GET /favicon.ico`.

**Comment by rhutchison** [comment] 2015-07-06 12:27
Close?

**Comment by lirantal** [comment] 2015-07-06 18:06
before we close we should still confirm if this is some bug or not.
@pgrodrigues @mg1075 can you confirm if it's working as expected?

**Comment by mg1075** [comment] 2015-07-06 19:16
Fine to close. 

The issue here that is kind of awkward from my perspective is how layout.server.view.html has its file paths altered. Another example is:
`<div ng-include="'/modules/core/views/header.client.view.html'"></div>`

The real folder path is `modules/core/client/views/header.client.view.html`, but again this path gets modified on the server. To people looking at the view the first time, this is not going to be immediately obvious.

**Comment by pgrodrigues** [comment] 2015-07-07 08:35
Both the favicon and the ng-include work but maybe the paths weren't updated from `0.3.0` to `0.4.0`. `0.3.0` seems to have the same paths as `0.4.0` despite the directory structure being different.

**Comment by codydaig** [comment] 2015-07-16 04:49
I'll make note to add this to the documentation. #443

**Comment by kimgeorge83** [comment] 2015-07-20 03:40
I'm not sure I understand why the /client is removed from the paths. It's not very intuitive. Could someone explain the rationale? I spent a long time trying to figure out why my paths weren't being found, I asked the question on stack exchange (http://stackoverflow.com/questions/31491925/angular-js-directive-templateurl-not-found-on-mean-js-stack/31508318#31508318).

**Comment by codydaig** [comment] 2015-07-20 06:32
This seems to be a common issue. I'm not sure why it removes the /client from the paths but you could change it in the config file if you want it back in on your project.

**Comment by kimgeorge83** [comment] 2015-07-20 21:18
No worries, I'll try changing it on my project, I'm just a bit worried I might break something. I'd really like to understand the rationale why this was done.

**Comment by mg1075** [comment] 2015-07-20 23:43
Doesn't the modification of the file path defeat the goal of quickly identifying files and destinations? I think it is better to have verbose path names rather than slightly less verbose path names that have their paths dynamically - and in a kind of sneaky way - altered. Again, it would be really helpful to know the thinking that went behind this design decision.

**Comment by kimgeorge83** [comment] 2015-07-21 02:50
@amoshaviv, it looks like you originally added the module static routes section in express.js, are you able to comment on the rationale for removing /client form the static paths? We are just trying to determine if we'll break anything by removing it on our projects.

**Comment by kimgeorge83** [comment] 2015-07-22 02:55
I modified the /client removal behavior and it doesn't seem to affect the site behavior. I'll let you know if I run into any issues. I updated the post here with details of the fix (http://stackoverflow.com/questions/31491925/angular-js-directive-templateurl-not-found-on-mean-js-stack/31508318#31508318). 

I can make the change to mean.js if people are interested but the yeoman module generator will also need to be modified since it generates modules with the paths missing the /client

**Comment by lirantal** [comment] 2015-07-22 17:20
@kimgeorge83  so I'm not sure if you are referring to an actual bug here or just question about convention.

@rhutchison @trainerbill do you have an idea how/if the /client affects anything?

**Comment by kimgeorgesb** [comment] 2015-07-22 17:24
It's not a bug it's just not a very intuitive convention to remove the /client from all the paths because it's not a real path, the designer has to know that's the convention. There doesn't appear to be any solid reason why that's the convention.

**Comment by danaronoff** [comment] 2015-07-22 17:34
I think the reason this was done was to maintain backwards compatibility with the current paths in the master branch. This convention allowed the public/modules folder to be moved to the current 0.4.0 structure without having to update any static routes in the views.

I can see the benefit in keeping it the way it is to ease the migration to 0.4.0 as long as it is documented. Anyway, in the current master branch, there is another convention being used which strips the leading public/ off the paths.

**Comment by trainerbill** [comment] 2015-07-22 19:21
+1 for closing.

**Comment by lirantal** [comment] 2015-07-22 19:34
I personally did the merge of 0.4.0 with master and while it could be that some things on the UI are broken - I didn't have any kind of conflict to resolve related to the /client paths.

I tend to agree with @kimgeorgesb about this thing not being very intuitive and anyone trying to learn the framework will find it hard so I don't want to just "toss it away".

If removing /client doesn't break anything and isn't holding us back then why not do so?

**Comment by danaronoff** [comment] 2015-07-22 19:51
Would that mean that all client side views would need to be updated to include 'client'?

**Comment by lirantal** [comment] 2015-07-22 19:52
I don't know, you tell me :-)
@kimgeorgesb didn't say anything about that, just that the /client is anyway being removed on the server side.

**Comment by kimgeorge83** [comment] 2015-07-22 20:01
I get the arguments for backwards compatibility. I had the luxury of starting my app with the 0.4 dev so I only had to correct the paths in the core. I imagine a production site would be a lot of work to update. 

I don't think there's any impact to the server side routes its only the client side paths that need to be updated. I'm gonna post a patch for the Yeoman generator so if people want to start with an 'unadulterated' code base they can.

**Comment by trainerbill** [comment] 2015-07-22 20:38
@mg1075 If you remove the 

```js
// Globbing static routing
	config.folders.client.forEach(function (staticPath) {
		app.use(staticPath.replace('/client', ''), express.static(path.resolve('./' + staticPath)));
	});
```

You get errors on all the controller loading because it is not looking for the client.  So you would also need to update where the application is inserting the script src="modules/core/controllers" etc to include the client piece.  You would also need to update all the references to the views.  I would consider this a very massive undertaking.  But I do agree that it does not make sense in its current form.  I will try and dig deeper.

**Comment by trainerbill** [comment] 2015-07-23 16:07
I think it makes a lot of sense to add the client back into the URLs, but I don't think we should attempt it for 0.4.0.  I say we close this PR or put it in a milestone for 0.5.0

**Comment by lirantal** [comment] 2015-07-24 08:22
@trainerbill thanks for looking into it, I'll add it to the 0.5.0 items

**Closed by lirantal** 2015-07-24 08:22 UTC

**Comment by trainerbill** [comment] 2015-08-04 22:06
PR for this issue created here:

https://github.com/meanjs/mean/pull/758

up for discussion
