### ISSUE TITLE
Facebook Login is not Working

### ISSUE THREAD

**Issue by benmarten** [meanjs/mean#697] opened 2015-07-24 13:56 UTC
The Facebook Login is not working and it does not throw any error in the console or web console.
The Facebook redirect works, but then in the application nothing is happening.
I have configured the App_id and secret. What's missing?

**Comment by benmarten** [comment] 2015-07-24 14:17
Ok, hunted it down to a missing e-mail: https://github.com/jaredhanson/passport-facebook/issues/129
And also this solution: https://github.com/meanjs/mean/issues/202

**Comment by lirantal** [comment] 2015-07-24 22:31
@benmarten on which branch is this? master or 0.4.0, and are you updated to the latest version there?

**Comment by benmarten** [comment] 2015-07-25 11:38
Ok, tested this real quick by cloning 0.4.0 branch and just configuring my fb app id.
It does not work. Only works when adding this line to passport.use(...):
    profileFields: ['email']
to config/strategies/facebook.js:18

**Comment by ilanbiala** [comment] 2015-07-25 12:59
@benmarten is that found in the FB docs too?

**Comment by codydaig** [comment] 2015-07-29 02:49
@benmarten Looking at the 0.4.0 code and the facebook strategy:
https://github.com/meanjs/mean/blob/0.4.0/modules/users/server/config/strategies/facebook.js#L16
it seems that the profileFields already includes 'email' in the array. What specifically needs to be changed?

**Comment by lirantal** [comment] 2015-07-29 14:11
@codydaig @benmarten it seems like your find matches the 'emails' profileField while @benmarten was showing success cases referrencing 'email' profileField (notice the plural vs singular use).

I'm unable to test as I don't have a FB account but we should fix this if it's an actual problem on 0.4.0
@benmarten can you look into making this change to 0.4.0 and submit a PR that fixes it? I would just add the 'email' element to that array in https://github.com/meanjs/mean/blob/0.4.0/modules/users/server/config/strategies/facebook.js#L16 and test it out.

**Comment by codydaig** [comment] 2015-08-19 07:59
@ilanbiala https://developers.facebook.com/docs/graph-api/reference/v2.3/user
There is no 'emails' field, it's only 'email'. 

@benmarten Do you want to create the PR against the master branch?

**Comment by codydaig** [comment] 2015-08-22 15:53
#839

**Comment by codydaig** [comment] 2015-08-23 17:13
@benmarten @lirantal I have tested this on the latest branch, and it works with 'emails' so I am unable to reproduce this issue.

**Comment by benmarten** [comment] 2015-08-23 19:58
Hey, so it seems that in latest master branch strategies/facebook.js is gone... I tested it again, and now i see the following error message:
<img width="960" alt="screen shot 2015-08-23 at 21 58 38" src="https://cloud.githubusercontent.com/assets/5960238/9429946/23a3b598-49e2-11e5-8396-0a0b1664bf20.png">

**Comment by rhutchison** [comment] 2015-08-23 20:21
@benmarten are you using the latest master?

https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/facebook.js

**Comment by benmarten** [comment] 2015-08-23 21:08
Hm, sorry I am confused...

https://github.com/meanjs/mean/tree/master/config/env it's not there?

	Ben@Bens-MacBook-Pro ~/N/mean> git checkout master
	M	config/env/development.js
	Already on 'master'
	Your branch is up-to-date with 'origin/master'.
	Ben@Bens-MacBook-Pro ~/N/mean> ls -l config/env/
	total 56
	-rw-r--r--  1 Ben  staff  2255 Aug 23 23:00 cloud-foundry.js
	-rw-r--r--  1 Ben  staff   887 Aug 23 23:00 default.js
	-rw-r--r--  1 Ben  staff  2217 Aug 23 23:01 development.js
	-rw-r--r--  1 Ben  staff   529 Aug 23 23:00 local.example.js
	-rw-r--r--  1 Ben  staff   529 Aug 23 23:04 local.js
	-rw-r--r--  1 Ben  staff  2197 Aug 23 23:00 production.js
	-rw-r--r--  1 Ben  staff  1939 Aug 23 23:00 test.js

**Comment by benmarten** [comment] 2015-08-23 21:21
Ah ok found it ;)

So first I see this issue:
    GET /api/auth/facebook?redirect_to=%2F 302 2.370 ms - 0
which seems to lead to the error in the screenshot from above.

Also the fb login is not working for me.

I tested it by putting some console.log() in the code and it seems that config/strategies/facebook.js isn't called anymore at all! Now only user.oauthCall() function is called...

**Comment by lirantal** [comment] 2015-08-23 21:23
@rhutchison seems related to the issue I recently merged about the previous page in history bug (https://github.com/meanjs/mean/commit/cfe71bb3de02ab10522b56bf671badab5110e9ff)

**Comment by benmarten** [comment] 2015-08-25 00:02
Just a wild guess, but i think that passport seems to be called directly now from here:
https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L97

instead the facebook.js stuff should be called from that line, shouldn't it?

**Comment by rhutchison** [comment] 2015-08-25 05:02
@benmarten @lirantal what are the steps to reproduce?

I am unable to reproduce in my environment, but I might be missing something.

@benmarten are you sure your facebook config/callback url are setup correctly in the configuration?  When you see the page not found, what is the URL in the address bar?

**Comment by rhutchison** [comment] 2015-08-25 05:16
@benmarten please make sure your environment config is updated to reflect [this change](https://github.com/meanjs/mean/pull/841/files)

**Comment by mleanos** [comment] 2015-08-25 05:30
@rhutchison I've tested these changes from #842 , and everything seems to be working fine for me. Although, I experienced the Page Not Found issue before I had updated my local env config to use the correct callback URL... `callbackURL: '/api/auth/facebook/callback'` Perhaps this is the cause of @benmarten issue.

**Comment by benmarten** [comment] 2015-08-25 11:42
indeed. that fixes the issue also for me. so basically only uncommenting local.js solved it...

**Comment by lirantal** [comment] 2015-08-25 12:45
Great, so this is good to merge.
Thanks for testing and feedback guys.

**Closed** 2015-08-25 13:14 UTC
Labels: bug

**Comment by AmaliDeveloper** [comment] 2017-03-13 00:36
You can get the solution here Facebook SDK connect [Link](https://youtu.be/xKC5pFEpH2A)
