### ISSUE TITLE
OAuth Login Issues  Error: /api/auth/google/[object%20Object] is not a valid path.

### ISSUE THREAD

**Issue by ChrisMaher** [meanjs/mean#1290] opened 2016-04-03 17:57 UTC
Hi

Ive been working on a project for a while and this problem just popped up. Im not sure how far back the problem occured or on what commit.

When someone logs in with Facebook or Google it redirects to the server 404 page and shows

`Page not found  Error: /api/auth/google/[object%20Object] is not a valid path.`

However if i refresh the page the user is logged in.

**Comment by iamchriswick** [comment] 2016-04-04 18:25
I'm experiencing the same issue...

**Comment by mrbfrank** [comment] 2016-04-04 18:27
This issue is related/duplicate of https://github.com/meanjs/mean/issues/1284

**Comment by thodinh** [comment] 2016-04-22 03:02
Refer to `users.authentication.server.controller.js   >>>   exports.oauthCallback` 
Considering the return redirect 

> `return res.redirect(redirectURL || sessionRedirectURL || '/');`

I debugged and found that `redirectURL `received is an object `{}` (it is not actually `null `or `undefined`). So `redirectURL `will be return in conditional expression `redirectURL || sessionRedirectURL || '/'`

My solution for this issue is: check type of redirectURL is string or not

> `return res.redirect(typeof redirectURL == 'string' ? redirectURL : sessionRedirectURL || '/');`

**Comment by abaka82** [comment] 2016-08-24 07:30
thanks @thodinh. Your solution is perfect for this social account issue

**Comment by lirantal** [comment] 2016-08-27 21:23
closed via #1284 
@ChrisMaher can you confirm that this issue is fixed in the `master` branch?

**Closed by lirantal** 2016-08-27 21:23 UTC
Labels: feedback:question, issue:bug

**Comment by o1lab** [comment] 2016-09-13 15:03
Thank you @thodinh

**Comment by brianpgerson** [comment] 2016-10-16 23:02
FYI, this is still `return res.redirect(redirectURL || sessionRedirectURL || '/');` on 0.4.2. Updated local code with the fix here and it worked.
