### ISSUE TITLE
Deployment to IBM Bluemix fails

### ISSUE THREAD

**Issue by Brian1111** [meanjs/mean#1441] opened 2016-08-23 17:23 UTC
I can upload the code from Git terminal, but after "Uploading droplet" message, no instance is running.  I can manually run the instance from Bluemix website, but after clicking the URL, it states:  "Requested route does not exist."

I was able to deploy my code to Heroku after looking at the closed issue, which suggested to add gulp dependencies from devDependencies to Dependencies.  However, the same code does not work for Bluemix.

I was able to upload mean.js 0.4.2 to Bluemix, so the problem is with mean.js 0.5.0-beta.

**Comment by lirantal** [comment] 2016-08-24 16:16
@Brian1111 can you help us with more debug information about what would be the problem? logs or something?

**Comment by Brian1111** [comment] 2016-08-24 19:26
I deleted everything.  I am using mean-0.4.2, which is now on Bluemix.  Have you been able to deploy mean-0.5.0-beta to Bluemix?  In addition to this, mean-0.5.0-beta Article does not have Create and Edit functions.

Also, I haven't been able to deploy mean-0.4.2 to Heroku; I could only deploy it to Bluemix.

**Comment by lirantal** [comment] 2016-08-24 21:02
I don't have a way to reproduce the issue with Bluemix, so no I can't test it and need your help.
Is it something you can try again and report back with more actual evidence of what's going wrong?

**Comment by codydaig** [comment] 2016-08-24 23:29
@ryanjbaxter

**Comment by ryanjbaxter** [comment] 2016-08-24 23:30
Sorry guys, I no longer work for IBM, so my focus is elsewhere

**Comment by codydaig** [comment] 2016-08-24 23:32
@lirantal I would like to make a proposal to remove Bluemix then since we can't practically support it and it seems to break frequently.

**Comment by Brian1111** [comment] 2016-08-25 07:34
I can easily connect mean-0.4.2 to Bluemix.  Bluemix is much faster than Heroku, so I prefer it to Heroku.

**Comment by lirantal** [comment] 2016-08-25 14:54
@codydaig understood but I do wonder if this is something we can test somehow or have a community member help with testing it.
@Brian1111 can you test the master branch of MEAN.JS with bluemix and provide us more details and logs on whats going wrong?

**Comment by Brian1111** [comment] 2016-08-25 16:16
@lirantal I just deployed mean-0.5.0-beta to bluemix.  I enclosed the last error messages in the png file.

![mean-0 5 0-beta_error_messages](https://cloud.githubusercontent.com/assets/12651236/17976806/d8d0619a-6aa3-11e6-80ad-e2ede194fcb8.png)

**Comment by lirantal** [comment] 2016-08-25 18:49
@Brian1111 Thanks.
It seems that the bluemix environment doesn't have gulp installed. Can you install it and run the application again to test it?

**Comment by Brian1111** [comment] 2016-08-25 19:44
I did move gulp and its dependencies from devDependencies to Dependencies to make it run on Heroku, as I stated in my original statement.    It runs on Heroku, but not on Bluemix.  Here are the modules that I added, and the errors I am getting after deployment to Bluemix:


![mean-0 5 0-beta_error_messages-2](https://cloud.githubusercontent.com/assets/12651236/17983320/d68584d4-6ac0-11e6-9fbd-07fe63b4ff79.png)

![gulp-and-its-dependencies](https://cloud.githubusercontent.com/assets/12651236/17983434/723d5c1c-6ac1-11e6-8829-8e917b461d10.png)

**Comment by simison** [comment] 2016-08-25 21:02
FYI: If you try to start the app using `gulp` command directly, it expects to find global Gulp installed. If you use `npm start` instead, it would use gulp installed locally to node_modules (and thus moving it to dependencies is required).

**Comment by lirantal** [comment] 2016-08-26 06:41
@Brian1111 can you pull the branch of my PR in https://github.com/meanjs/mean/pull/1449 and try to use that to push to bluemix and build there?

**Comment by Brian1111** [comment] 2016-08-26 23:22
@lirantal  What do you mean by "pull the branch of my PR in #1449"? I replaced .bluemix/pipeline.yml file with the one that you posted; is it what you mean?  Still the deployment fails.

**Comment by lirantal** [comment] 2016-08-27 07:13
Sure it's ok if you also replace it with your local one for testing.
I'll need you to always post back the logs and errors you get after you try so I can figure out what is failing there.

**Comment by Brian1111** [comment] 2016-08-27 16:35
I replaced pipeline.yml with the one that you posted.  Here are the last errors:

![mean-w-pipeline yml errors](https://cloud.githubusercontent.com/assets/12651236/18028635/15b2d674-6c39-11e6-8ba0-6a43a192d46f.png)

**Comment by lirantal** [comment] 2016-08-27 16:37
@Brian1111 ok, got it.
I just made another commit on that branch, can you use again my updated file and test?

**Comment by Brian1111** [comment] 2016-08-27 17:03
I added the new pipeline.yml file at the directory meanjs/.bluemix/pipeline.yml.  Here are the errors:

![mean-w-pipeline yml_errors2](https://cloud.githubusercontent.com/assets/12651236/18028868/72f7d8ee-6c3d-11e6-8045-dce10aa566df.png)

**Comment by lirantal** [comment] 2016-08-27 17:06
Are you sure you stepped through the build process which does an npm install from the start? That dev dependency is still missing according to the log you show me.

**Comment by Brian1111** [comment] 2016-08-27 17:13
Isn't npm get installed on Bluemix?  Why should I install it on localhost?  All I did was I typed "cf push".  Regarding devDependencies, aren't they supposed to run only on localhost?

**Comment by Brian1111** [comment] 2016-08-27 17:29
Regarding Dependencies, my gulp dependencies version in Dependencies are different from the ones in devDependencies.   The ones in devDependencies are the ones that are already there, but the ones in Dependencies are the ones that I copied from you when you solved the issue for deployment to Heroku.   I did run npm install and then typed cf push.   Here are the last errors:


![mean-w-pipeline yml_errors3](https://cloud.githubusercontent.com/assets/12651236/18029016/0738f648-6c41-11e6-993c-49f67a9b85a7.png)

**Comment by Brian1111** [comment] 2016-08-27 17:34
I double checked gulp dependencies in both Dependencies & devDependencies; they are the same.  Sorry for the mistake.   Here are the dependencies:

![gulp_dependencies](https://cloud.githubusercontent.com/assets/12651236/18029030/b38a9b40-6c41-11e6-94d0-2ffc037aa36d.png)

**Comment by lirantal** [comment] 2016-08-27 21:05
what does `cf-push` ends up doing? can you explain?

**Comment by Brian1111** [comment] 2016-08-27 22:31
Here is the summary: (1) Using manifest file manifest.yml, (2) Updating app mean, (3) Creating route mean-leakless-preinspector.mybluemix.net (result OK), (5) Binding mean-leakless-preinspector.myblumix.net to mean (result OK), (6) Uploading mean from mean-master (Done uploading OK), (7) Binding service mean-mongo to app mean (result OK), (8) Stopping app mean (result OK), (8) Starting app mean: Downloaded app package (228k), Downloaded app buildpack cache (56M).  Then the rest are here:

![cf_push_report_1](https://cloud.githubusercontent.com/assets/12651236/18030428/aa73fcda-6c6a-11e6-8cff-b7c8085d244f.png)

![cf_push_report_2](https://cloud.githubusercontent.com/assets/12651236/18030429/b097360e-6c6a-11e6-98d8-067f9eb8b8d1.png)

![cf_push_report_3](https://cloud.githubusercontent.com/assets/12651236/18030431/b8e00908-6c6a-11e6-9605-ae24e9ba011f.png)

**Comment by ryanjbaxter** [comment] 2016-08-28 11:15
Perform a 'cf logs' command while doing a 'cf push'

**Comment by Brian1111** [comment] 2016-08-28 15:28
I have already performed  'cf logs mean --recent', which I posted above.  If you mean that I have to type both commands at once, then how should I type it?  Have you been able to deploy mean-0.5.0-beta to Bluemix successfully yourself?

**Comment by ryanjbaxter** [comment] 2016-08-28 16:23
I mean that you run both command simultaneously in two different terminal
Windows so you can see the logs as the deployment happens. I have not tried
deploying it to bluemix since I have left IBM and my role has changed. If j
have some time I might be able to give it a go

**Comment by Brian1111** [comment] 2016-08-28 17:21
I ran them side  by side.  Here are the errors in cf logs:

![cf_logs_errors_run_w_cf_push1](https://cloud.githubusercontent.com/assets/12651236/18035329/0b0567b6-6d09-11e6-8275-1de70a32534e.png)

![cf_logs_errors_ran_w_cf_push2](https://cloud.githubusercontent.com/assets/12651236/18035332/1285659a-6d09-11e6-9b7c-4eb368a2792b.png)

![cf_logs_errors_ran_w_cf_push3](https://cloud.githubusercontent.com/assets/12651236/18035336/1bec07b0-6d09-11e6-8f9f-6d7ada994c53.png)

**Comment by wangmeng** [comment] 2016-08-31 04:53
Hi Brian, 
You also need to check the package.json file, and since during the runtime of latest version, by default, it require "gulp, run-sequence, imagemin-pngquant", which are not listed in dependencies. You may need to add them. 

Here are mine version, fyr


  "dependencies": {
    "acl": "~0.4.9",
    "async": "~1.5.2",
    "body-parser": "~1.15.0",
    "bower": "~1.7.7",
    "cfenv": "~1.0.3",
    "chalk": "~1.1.1",
    "compression": "~1.6.1",
    "connect-flash": "~0.1.1",
    "connect-mongo": "~1.1.0",
    "consolidate": "~0.14.0",
    "cookie-parser": "~1.4.1",
    "crypto": "0.0.3",
    "express": "~4.14.0",
    "express-session": "~1.13.0",
    "file-stream-rotator": "~0.0.6",
    "generate-password": "~1.1.1",
    "glob": "~7.0.0",
    "grunt": "~1.0.1",
    "grunt-cli": "~1.2.0",
    "gulp": "~3.9.1",
    "gulp-angular-templatecache": "~1.8.0",
    "gulp-autoprefixer": "~3.1.0",
    "gulp-concat": "~2.6.0",
    "gulp-csslint": "~0.2.0",
    "gulp-csso": "~1.1.0",
    "gulp-eslint": "~2.0.0",
    "gulp-imagemin": "~2.4.0",
    "gulp-less": "~3.0.5",
    "gulp-livereload": "~3.8.1",
    "gulp-load-plugins": "~1.2.0",
    "gulp-mocha": "~2.2.0",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-nodemon": "~2.0.6",
    "gulp-protractor": "~2.1.0",
    "gulp-rename": "~1.2.2",
    "gulp-sass": "~2.2.0",
    "gulp-uglify": "~1.5.2",
    "gulp-util": "~3.0.7",
    "gulp-node-inspector": "~0.1.0",
    "helmet": "~1.3.0",
    "jasmine-core": "~2.4.1",
    "lodash": "~4.6.1",
    "lusca": "~1.3.0",
    "method-override": "~2.3.5",
    "mocha": "~2.5.0",
    "mongoose": "~4.4.8",
    "morgan": "~1.7.0",
    "multer": "~1.1.0",
    "nodemailer": "~2.3.0",
    "owasp-password-strength-test": "~1.3.0",
    "passport": "~0.3.2",
    "passport-facebook": "~2.1.0",
    "passport-github": "~1.1.0",
    "passport-google-oauth": "~1.0.0",
    "passport-linkedin": "~1.0.0",
    "passport-local": "~1.0.0",
    "passport-paypal-openidconnect": "~0.1.1",
    "passport-twitter": "~1.0.4",
    "phantomjs-prebuilt": "~2.1.4",
    "serve-favicon": "~2.3.0",
    "socket.io": "~1.4.5",
    "swig": "~1.4.2",
    "validator": "~5.1.0",
    "winston": "^2.2.0",
    "run-sequence": "~1.1.5",
    "imagemin-pngquant": "~4.2.0",
    "karma": "~0.13.21",
    "karma-chrome-launcher": "~0.2.2",
    "karma-coverage": "~0.5.3",
    "karma-firefox-launcher": "~0.1.7",
    "karma-jasmine": "~0.3.7",
    "karma-ng-html2js-preprocessor": "~0.2.1",
    "karma-phantomjs-launcher": "~1.0.0",
    "eslint": "~2.2.0",
    "eslint-config-airbnb": "~6.0.2",
    "wiredep": "~4.0.0"
  },

**Comment by lirantal** [comment] 2016-08-31 18:32
@Brian1111 Sorry it seems to be very hard to help without using this service and understanding what's going on.

I think that what's happening is that you may not have all the `devDependencies` installed. Is it somehow possible to list the `node_modules/` directory before running the app? Maybe it can point us in to some direction.

**Comment by lirantal** [comment] 2016-08-31 18:33
@wangmeng what do you mean? `run-sequence` is part of the devDependencies.

**Comment by wangmeng** [comment] 2016-09-01 00:24
@lirantal I tried to deploy a mean project to Bluemix, the section is what I used to make it work. 
If you check @Brian1111 last comment, the cf log mentioned "Cannot find module run-sequence". 

I can follow up from Bluemix side, if anything. Thanks.

**Comment by lirantal** [comment] 2016-09-01 20:11
@wangmeng so you moved the `run-sequence` and possibly other packages from the `devDependencies' section to the `dependencies`? Even if so, this isn't something we can do in the project and we need to find the right configuration for it in the bluemix file.

**Comment by wangmeng** [comment] 2016-09-02 18:47
@lirantal I agree your point, it is just a way to get the deployment work, but not a solution. 

I spent some time, and tried with the updated pipeline.yml file. The steps I did are as blow:

1. Use the hub.jazz.net to clone the mean repo, in this way, the build & deploy task will be created
https://bluemix.net/deploy?repository=https%3A%2F%2Fgithub.com%2Fmeanjs%2Fmean
2. Update pipeline.yml in the private repo
3. Run the build pipeline, which can work well. 
4. Run the deploy pipeline, which will be failed.
5. I attached both build & deploy logs here as attachment, as well as the pipeline.yml (which I changed the extension for upload reason)
[build pipeline.txt](https://github.com/meanjs/mean/files/452698/build.pipeline.txt)
[deploy pipeline.txt](https://github.com/meanjs/mean/files/452697/deploy.pipeline.txt)
[pipeline.yml.txt](https://github.com/meanjs/mean/files/452700/pipeline.yml.txt)

6. When run the `cf logs mean-mengw-124 --recent`
The error I got is:
2016-09-03T02:27:30.48+0800 [App/0]      ERR sh: 1: gulp: not found
2016-09-03T02:27:30.52+0800 [App/0]      ERR npm ERR! Linux 3.19.0-33-generic
2016-09-03T02:27:30.52+0800 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! node v4.4.7
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! npm  v3.10.6
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! file sh
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-09-03T02:27:30.56+0800 [App/0]      ERR npm ERR! errno ENOENT
2016-09-03T02:27:30.56+0800 [App/0]      ERR npm ERR! syscall spawn
2016-09-03T02:27:30.56+0800 [App/0]      ERR npm ERR! meanjs@0.5.0-beta start: `gulp`
2016-09-03T02:27:30.56+0800 [App/0]      ERR npm ERR! spawn ENOENT
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! 
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! Failed at the meanjs@0.5.0-beta start script 'gulp'.
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! If you do, this is most likely a problem with the meanjs package,
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! not with npm itself.
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-09-03T02:27:30.57+0800 [App/0]      ERR npm ERR!     gulp
2016-09-03T02:27:30.58+0800 [App/0]      ERR npm ERR! You can get information on how to open an issue for this project with:
2016-09-03T02:27:30.58+0800 [App/0]      ERR npm ERR!     npm bugs meanjs
2016-09-03T02:27:30.58+0800 [App/0]      ERR npm ERR! Or if that isn't available, you can get their info via:
2016-09-03T02:27:30.58+0800 [App/0]      ERR npm ERR!     npm owner ls meanjs
2016-09-03T02:27:30.58+0800 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-09-03T02:27:30.59+0800 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-09-03T02:27:30.59+0800 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-09-03T02:27:30.70+0800 [DEA/24]     ERR Instance (index 0) failed to start accepting connections


**The unexpected behavior is:**
**In the build pipeline, I can see node version is 0.12, and gulp is installed:**
gulp@3.9.1 node_modules/gulp
├── interpret@1.0.1
├── pretty-hrtime@1.0.2
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.2.0 (os-homedir@1.0.1)
├── minimist@1.2.0
├── v8flags@2.0.11 (user-home@1.1.1)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.3.0 (lodash.isstring@4.0.1, lodash.isplainobject@4.0.6, rechoir@0.6.2, extend@3.0.0, flagged-respawn@0.3.2, lodash.mapvalues@4.6.0, resolve@1.1.7, fined@1.0.1, findup-sync@0.4.2)
└── vinyl-fs@0.3.14 (strip-bom@1.0.0, defaults@1.0.3, graceful-fs@3.0.11, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)


**But during the deploy phase, and according to cf logs output, somehow the env is using back to node 4.4.7:**

2016-09-03T02:27:30.33+0800 [App/0]      OUT > gulp
2016-09-03T02:27:30.48+0800 [App/0]      ERR sh: 1: gulp: not found
2016-09-03T02:27:30.52+0800 [App/0]      ERR npm ERR! Linux 3.19.0-33-generic
2016-09-03T02:27:30.52+0800 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! node v4.4.7
2016-09-03T02:27:30.55+0800 [App/0]      ERR npm ERR! npm  v3.10.6

**Comment by lirantal** [comment] 2016-09-02 20:24
Maybe we can find some references in other, *working* pipeline configs?

**Comment by lirantal** [comment] 2016-09-03 22:37
@Brian1111 @wangmeng I am going to close and remove any Bluemix related integration we have as it is simply not working and there's no one to test/confirm it.

If you end up figuring it out I welcome your PRs to support it.

**Closed by lirantal** 2016-09-03 22:37 UTC
Labels: feedback:question, issue:bug

**Comment by wangmeng** [comment] 2016-09-04 07:40
@lirantal @Brian1111 I will look into if any solution, and come back. Thx.

**Comment by Brian1111** [comment] 2016-09-05 20:20
@lirantal Can you ask Bluemix engineers to fix this?  I use mean-0.4.2 only on Bluemix as it is much faster than Heroku.  Is it possible that the problem is caused because mean-0.5.0 uses gulp instead of grunt?

**Comment by simison** [comment] 2016-09-05 20:28
@Brian1111 could you? ;-)

**Comment by wangmeng** [comment] 2016-09-06 20:43
@Brian1111 I have reopened the issue you raised for Bluemix, will follow up that one. 
@lirantal @simison I will update the progress later, if any proper solution.  
Thanks

**Comment by Brian1111** [comment] 2016-09-07 01:28
I just got an email from Bluemix in which they said they will investigate the issue.

**Comment by Brian1111** [comment] 2016-09-07 02:02
@lirantal @simison Wang Meng is an engineer from Bluemix who was in contact with me through email.

**Comment by lirantal** [comment] 2016-09-07 20:48
Cool, so let's figure it out and we can re-open this issue when it becomes more clear as to resolving the problem.

**Comment by idan666** [comment] 2016-10-19 15:43
Hey,
Is there an update on the matter?
Been struggling with the same "gulp: not found" issue during pushing to Bluemix.
I really enjoy their service, so i would hate to replace them.
Cheers.

**Comment by lirantal** [comment] 2016-10-19 15:52
Unless someone can provide a PR with the relevant fixes for making the deployment work, and actually test it we can't "fix it on our own".

You're welcome to help.

**Comment by vinodkhandelwal** [comment] 2017-03-15 09:27
Hey,
Is there an update on this?
Sill struggling with the same "gulp: not found" issue during pushing to Bluemix.
Cheers.

**Comment by simison** [comment] 2017-03-15 09:32
>Is there an update on this?

Any updates would be mentioned in this thread.

PR's totally welcome! ✨
