### ISSUE TITLE
In 0.4.0 and master getting "Cannot find module when running mocha test" on grunt or gulp

### ISSUE THREAD

**Issue by MangeshMp** [meanjs/mean#312] opened 2014-12-18 05:49 UTC
When we try to run mocha test using grunt or gulp you get a missingschema error on Article and User.
```MissingSchemaError: Schema hasn't been registered for model "Article".```
Use mongoose.model(name, schema).

**Comment by ilanbiala** [comment] 2015-01-08 00:45
@JuanCaicedo is spot on. @MangeshMp you need to get the database connection set up. With 0.4.0 it should be easier because you can use `config/lib/mongoose.js` to connect and inside the callback run Mocha. Can you try that out to see if it works?

**Comment by MangeshMp** [comment] 2015-01-08 06:15
HI @JuanCaicedo,

I did't get you.
I added  below lines in article.server.model.tests.js

In 0.4.0
var path = require('path');
var User = require(path.resolve('./modules/users/server/models/user.server.model'));
var Article = require(path.resolve('./modules/articles/server/models/article.server.model'));

When I try to debug using webstorm all the mocha tests stalls and fails after 2 sec.

Error: Required MongoStore option `db` missing
    at new MongoStore (C:\GitHub\mean\mean\mean\mean\node_modules\connect-mongo\lib\connect-mongo.js:104:15)
    at Object.module.exports.initSession (C:\GitHub\mean\mean\mean\mean\config\lib\express.js:115:10).

Where do I set up the data.

**Comment by JuanCaicedo** [comment] 2015-01-08 15:47
Could you share your mocha test? I'm debugging mine too and I'll keep you updated with what I'm doing.

As for the db error, I think the problem is that the line `app = express.init(mongoose)` is wrong. Based on how the app is initialized in `server.js`, I'm trying to replace the whole `before` statement with: 
````
	before(function(done) {
		// Initialize mongoose
		mongoose.connect(function(db) {
			// Get application
			app = express.init(db);
			agent = request.agent(app);
		});

		done();
	});
````

But I'm getting timeout errors on all my tests.

**Comment by JuanCaicedo** [comment] 2015-01-08 16:27
Are you running your tests with `grunt mocha`?

**Comment by MangeshMp** [comment] 2015-01-10 05:31
Hi @JuanCaicedo 
The Test with Grunt mocha works fine.
But when i want to debug and step through the code using WebStorm it gives me this error.

**Comment by MangeshMp** [comment] 2015-01-10 19:02
This is the error i get when I run it using WebStorm

Error: Required MongoStore option `db` missing
    at new MongoStore (C:\GitHub\mean\mean\node_modules\connect-mongo\lib\connect-mongo.js:104:15)
    at Object.module.exports.initSession (C:\GitHub\mean\mean\config\lib\express.js:115:10)
    at Object.module.exports.init (C:\GitHub\mean\mean\config\lib\express.js:227:7)
    at Context.<anonymous> (C:\GitHub\mean\mean\modules\articles\tests\server\article.server.routes.tests.js:22:17)
    at Hook.Runnable.run (C:\GitHub\mean\mean\node_modules\mocha\lib\runnable.js:218:15)
    at next (C:\GitHub\mean\mean\node_modules\mocha\lib\runner.js:259:10)
    at Object._onImmediate (C:\GitHub\mean\mean\node_modules\mocha\lib\runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

**Comment by JuanCaicedo** [comment] 2015-01-10 19:21
Do you know what command Webstorm executes when it runs test? If it used `mocha <file>`, then it's not running through the normal set up for the tests.

**Comment by MangeshMp** [comment] 2015-01-10 19:59
Below is the command which webstorm uses.


"C:\Program Files\nodejs\node.exe" --debug-brk=4227
C:\GitHub\mean\mean\node_modules\mocha\bin\_mocha --recursive --timeout
259200000 --ui tdd --reporter "C:\Program Files (x86)\JetBrains\WebStorm
9.0.1\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js"
C:\GitHub\mean\mean\modules\articles\tests\server

On Sat, Jan 10, 2015 at 11:21 AM, Juan Caicedo <notifications@github.com>
wrote:

> Do you know what command Webstorm executes when it runs test? If it used mocha
> <file>, then it's not running through the normal set up for the tests.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/312#issuecomment-69468203>.
>



-- 
Thanks and Regards,
Mangesh Pimpalkar

**Comment by MangeshMp** [comment] 2015-01-10 20:00
Below is the command which webstorm uses.

"C:\Program Files\nodejs\node.exe" --debug-brk=4227
C:\GitHub\mean\mean\node_modules\mocha\bin\_mocha --recursive --timeout
259200000 --ui tdd --reporter "C:\Program Files (x86)\JetBrains\WebStorm
9.0.1\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js"
C:\GitHub\mean\mean\modules\articles\tests\server

**Comment by MangeshMp** [comment] 2015-01-10 20:02
![mochaerror](https://cloud.githubusercontent.com/assets/10228993/5693026/824f4482-98c0-11e4-9806-4d27fda6dc29.jpg)

**Comment by MangeshMp** [comment] 2015-01-12 06:24
I tried using the below settings and it works but somehow the debug hangs in Article crud beforeeach method.
![mochaerror](https://cloud.githubusercontent.com/assets/10228993/5699589/979fd9f2-99e0-11e4-9343-8a3b2aebc77f.jpg)

**Comment by JuanCaicedo** [comment] 2015-01-12 10:53
Try it with this, which is the mongoose task in the gulpfile: 	
````
before(function(done) {
	var mongoose = require('./config/lib/mongoose.js');

	mongoose.connect(function(db) {
		done();
	});
}
````

**Comment by MangeshMp** [comment] 2015-01-13 04:57
I tried to run mochaTest using gulp task it works but when I try to debug it hangs.

**Comment by ilanbiala** [comment] 2015-01-14 23:26
@MangeshMp can you paste in your `config/lib/express.js` file?

**Comment by MangeshMp** [comment] 2015-01-15 05:13
Hi @ilanbiala I downloaded 0.4.0 and ran the gulp test It works but find when you right click and run 'debug test' it throws error on "before all" hook.
i tried on multiple machine with same results.

Also did with webstorm configuration.It still fails.

**Comment by ilanbiala** [comment] 2015-01-15 15:58
What do you mean right click and run `debug test`...? Can you please paste the file I asked?

**Comment by MangeshMp** [comment] 2015-01-15 17:12
'use strict';

/**
 * Module dependencies.
 */
var config = require('../config'),
	express = require('express'),
	morgan = require('morgan'),
	bodyParser = require('body-parser'),
	session = require('express-session'),
	MongoStore = require('connect-mongo')(session),
	multer = require('multer'),
	favicon = require('serve-favicon'),
	compress = require('compression'),
	methodOverride = require('method-override'),
	cookieParser = require('cookie-parser'),
	helmet = require('helmet'),
	passport = require('passport'),
	flash = require('connect-flash'),
	consolidate = require('consolidate'),
	path = require('path');

/**
 * Initialize local variables
 */
module.exports.initLocalVariables = function (app) {
	// Setting application local variables
	app.locals.title = config.app.title;
	app.locals.description = config.app.description;
	app.locals.keywords = config.app.keywords;
	app.locals.googleAnalyticsTrackingID = config.app.googleAnalyticsTrackingID;
	app.locals.facebookAppId = config.facebook.clientID;
	app.locals.jsFiles = config.files.client.js;
	app.locals.cssFiles = config.files.client.css;

	// Passing the request url to environment locals
	app.use(function (req, res, next) {
		res.locals.host = req.protocol + '://' + req.hostname;
		res.locals.url = req.protocol + '://' + req.headers.host + req.originalUrl;
		next();
	});
};

/**
 * Initialize application middleware
 */
module.exports.initMiddleware = function (app) {
	// Showing stack errors
	app.set('showStackError', true);

	// Enable jsonp
	app.enable('jsonp callback');

	// Should be placed before express.static
	app.use(compress({
		filter: function (req, res) {
			return (/json|text|javascript|css/).test(res.getHeader('Content-Type'));
		},
		level: 9
	}));

	// Initialize favicon middleware
	app.use(favicon('./modules/core/client/img/brand/favicon.ico'));

	// Environment dependent middleware
	if (process.env.NODE_ENV === 'development') {
		// Enable logger (morgan)
		app.use(morgan('dev'));

		// Disable views cache
		app.set('view cache', false);
	} else if (process.env.NODE_ENV === 'production') {
		app.locals.cache = 'memory';
	}

	// Request body parsing middleware should be above methodOverride
	app.use(bodyParser.urlencoded({
		extended: true
	}));
	app.use(bodyParser.json());
	app.use(methodOverride());

	// Add the cookie parser and flash middleware
	app.use(cookieParser());
	app.use(flash());

	// Add multipart handling middleware
	app.use(multer({
		dest: './uploads/',
		inMemory: true
	}));
};

/**
 * Configure view engine
 */
module.exports.initViewEngine = function (app) {
	// Set swig as the template engine
	app.engine('server.view.html', consolidate[config.templateEngine]);

	// Set views path and view engine
	app.set('view engine', 'server.view.html');
	app.set('views', './');
};

/**
 * Configure Express session
 */
module.exports.initSession = function (app, db) {
	// Express MongoDB session storage
	app.use(session({
		saveUninitialized: true,
		resave: true,
		secret: config.sessionSecret,
		store: new MongoStore({
			db: db.connection.db,
			collection: config.sessionCollection
		})
	}));
};

/**
 * Invoke modules server configuration
 */
module.exports.initModulesConfiguration = function (app, db) {
	config.files.server.configs.forEach(function (configPath) {
		require(path.resolve(configPath))(app, db);
	});
};

/**
 * Configure Helmet headers configuration
 */
module.exports.initHelmetHeaders = function (app) {
	// Use helmet to secure Express headers
	app.use(helmet.xframe());
	app.use(helmet.xssFilter());
	app.use(helmet.nosniff());
	app.use(helmet.ienoopen());
	app.disable('x-powered-by');
};

/**
 * Configure the modules static routes
 */
module.exports.initModulesClientRoutes = function (app) {
	// Setting the app router and static folder
	app.use('/', express.static(path.resolve('./public')));

	// Globbing static routing
	config.folders.client.forEach(function (staticPath) {
		app.use(staticPath.replace('/client', ''), express.static(path.resolve('./' + staticPath)));
	});
};

/**
 * Configure the modules ACL policies
 */
module.exports.initModulesServerPolicies = function (app) {
	// Globbing policy files
	config.files.server.policies.forEach(function (policyPath) {
		require(path.resolve(policyPath)).invokeRolesPolicies();
	});
};

/**
 * Configure the modules server routes
 */
module.exports.initModulesServerRoutes = function (app) {
	// Globbing routing files
	config.files.server.routes.forEach(function (routePath) {
		require(path.resolve(routePath))(app);
	});
};

/**
 * Configure error handling
 */
module.exports.initErrorRoutes = function (app) {
	// Assume 'not found' in the error msgs is a 404. this is somewhat silly, but valid, you can do whatever you like, set properties, use instanceof etc.
	app.use(function (err, req, res, next) {
		// If the error object doesn't exists
		if (!err) return next();

		// Log it
		console.error(err.stack);

		// Redirect to error page
		res.redirect('/server-error');
	});

	// Assume 404 since no middleware responded
	app.use(function (req, res) {
		// Redirect to not found page
		res.redirect('/not-found');
	});
};

/**
 * Configure Socket.io
 */
module.exports.configureSocketIO = function (app, db) {
	// Load the Socket.io configuration
	var server = require('./socket.io')(app, db);

	// Return server object
	return server;
};

/**
 * Initialize the Express application
 */
module.exports.init = function (db) {
	// Initialize express app
	var app = express();

	// Initialize local variables
	this.initLocalVariables(app);

	// Initialize Express middleware
	this.initMiddleware(app);

	// Initialize Express view engine
	this.initViewEngine(app);

	// Initialize Express session
	this.initSession(app, db);

	// Initialize Modules configuration
	this.initModulesConfiguration(app);

	// Initialize Helmet security headers
	this.initHelmetHeaders(app);

	// Initialize modules static client routes
	this.initModulesClientRoutes(app);

	// Initialize modules server authorization policies
	this.initModulesServerPolicies(app);

	// Initialize modules server routes
	this.initModulesServerRoutes(app);

	// Initialize error routes
	this.initErrorRoutes(app);

	// Configure Socket.io
	app = this.configureSocketIO(app, db);

	return app;
};

**Comment by MangeshMp** [comment] 2015-01-15 17:18
![mochaerror](https://cloud.githubusercontent.com/assets/10228993/5762525/6e8632dc-9c97-11e4-8b7a-0d2354d68eaf.jpg)

**Comment by ilanbiala** [comment] 2015-01-15 17:19
@MangeshMp the issue is on line 115 of that file. There were some issues with this version of [kcbanner/connect-mongo](kcbanner/connect-mongo), so try upgrading to 0.6.0 and updating lines 115-118 accordingly.

**Comment by MangeshMp** [comment] 2015-01-20 06:06
I tried doing this but no luck .gives the same error.

**Comment by ilanbiala** [comment] 2015-01-20 11:57
Code?

**Comment by MangeshMp** [comment] 2015-01-21 06:36
I updated the connect-mongo to 0.6.0 and updated the code on line 115-118.Tried different combinations.

```
                       store: new MongoStore({
                          url: 'mongodb://localhost/mean-test'
                       })

```
I am getting error.

```      
 [22:29:05] 'mocha' errored after 44 s
 [22:29:05] Error in plugin 'gulp-mocha'
 Message:
    1 test failed.
[22:29:05] 'test1' errored after 45 s
[22:29:05] Error: [object Object]
    at formatError (C:\GitHub\mean\mean\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\GitHub\mean\mean\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at Orchestrator._runTask (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\index.js:275:23)
    at module.exports.finish (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports.cb (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (c:\GitHub\mean\mean\node_modules\run-sequence\index.js:48:5)
    at Gulp.onError (c:\GitHub\mean\mean\node_modules\run-sequence\index.js:55:4)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at Orchestrator._runTask (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\index.js:275:23)
    at module.exports.finish (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at Stream.module.exports (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:52:4)
    at Stream.f (c:\GitHub\mean\mean\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at Stream.emit (events.js:117:20)
  1 failing

  1) Article CRUD tests "before all" hook:
     Error: timeout of 2000ms exceeded
      at done (c:\GitHub\mean\mean\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:205:67)
      at c:\GitHub\mean\mean\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:226:9
      at Context.credentials.username (c:\GitHub\mean\mean\modules\articles\tests\server\article.server.routes.tests.js:29:3)
      at Hook.Runnable.run (c:\GitHub\mean\mean\node_modules\gulp-mocha\node_modules\mocha\lib\runnable.js:217:15)
      at next (c:\GitHub\mean\mean\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:258:10)
      at Object.Runner.hook [as _onImmediate] (c:\GitHub\mean\mean\node_modules\gulp-mocha\node_modules\mocha\lib\runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)

```

**Comment by ilanbiala** [comment] 2015-01-21 11:45
Now either your test is missing something or the code actually takes too long and the timeout has to be raised.

**Comment by MangeshMp** [comment] 2015-01-23 07:39
The error seems to be while loading acl.

**Comment by jessebuitenhuis** [comment] 2015-02-13 19:18
I was having this issue while running my tests in Webstorm 9.0.3. `grunt test:server` runs just fine, but when setting up the mocha task in Run/Debug Configurations I got the error `MissingSchemaError: Schema hasn't been registered for model "Article".`

Gruntfile.js
    mochaTest: {
			src: watchFiles.mochaTests,
			options: {
				reporter: 'spec',
				require: 'server.js'
			}
		},

I noticed the 'require' option - adding `--require server.js` in the Run/Debug Configurations in the 'Extra Mocha Options' solved my problems.

**Comment by bagnier** [comment] 2015-02-15 00:02
I have similar issues on 0.4.

```
grunt test
Running "env:test" (env) task

Running "mongoose" task

Application loaded using the "test" environment configuration

Running "mochaTest:src" (mochaTest) task

  Article Model Unit Tests:
    Method Save
      ✓ should be able to save without problems
      ✓ should be able to show an error when try to save without title

  Article CRUD tests
    1) "before all" hook

  User Model Unit Tests:
    Method Save
      ✓ should begin with no users
      ✓ should be able to save without problems
      ✓ should fail to save an existing user again (66ms)
      ✓ should be able to show an error when try to save without first name

  6 passing (7s)
  1 failing

  1) Article CRUD tests "before all" hook:
     Error: timeout of 2000ms exceeded
      at done (/vagrant/application/node_modules/mocha/lib/runnable.js:206:67)
      at /vagrant/application/node_modules/mocha/lib/runnable.js:227:9
      at Context.<anonymous> (/vagrant/application/modules/articles/tests/server/article.server.routes.tests.js:25:3)
      at Hook.Runnable.run (/vagrant/application/node_modules/mocha/lib/runnable.js:218:15)
      at next (/vagrant/application/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/vagrant/application/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

Warning: Task "mochaTest:src" failed. Used --force, continuing.

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket Y3Lov_DUxqEkHSneh5Ig with id 78439452
PhantomJS 1.9.8 (Linux): Executed 12 of 12 SUCCESS (0.009 secs / 0.099 secs)

Done, but with warnings.
```

**Comment by ilanbiala** [comment] 2015-02-15 00:11
@bagnier take a look at the paths in the error stack trace.

**Comment by bagnier** [comment] 2015-02-15 00:42
The application is your current 0.4.0 branch, as it is. The only piece of code mentioned into the stacktrace and out of the node_modules is modules/articles/tests/server/article.server.routes.tests.js. 

this is the snippet:
```javascript
	before(function(done) {
		// Get application
		app = express.init(mongoose);
		agent = request.agent(app);

		done();
	});
```

It seems that express.init(mongoose) is taking a while. If I invoke "grunt" instead of "grunt test" the launch takes about 2 minutes and finally works.

**Comment by TsarS** [comment] 2015-04-06 12:43
Same error in tests  
         Article CRUD tests "before all" hook
          Error: timeout of 2000ms exceeded

**Comment by lirantal** [comment] 2015-07-17 10:40
@MangeshMp all tests run ok now on 0.4.0 branch so I'm closing.
If you are still having any issues there please re-open.

**Closed by lirantal** 2015-07-17 10:40 UTC
Labels: question
