### ISSUE TITLE
Support new Angular versions 1.3, 2.0

### ISSUE THREAD

**Issue by ramusus** [meanjs/mean#335] opened 2014-12-29 10:05 UTC
What about porting stack to Angular 1.3 ? or directly Angular 2.0. Is there any known problems with it? May be someone already did this?

**Comment by ramusus** [comment] 2015-01-01 08:40
yes, I also updated and tests passed without errors
I only worry about how angular-bootstrap works with angular 1.3

**Comment by JuanCaicedo** [comment] 2015-01-06 19:41
I'm still unable to run them.  I get the following error:
`Error: [$location:nobase] $location in HTML5 mode requires a <base> tag to be present!`

I think this is a bug because I can get each module to pass individually. Have any of you had that error?

**Comment by ilanbiala** [comment] 2015-01-08 00:53
@JuanCaicedo do you have a base tag in the layout HTML view? That is a breaking change that happened in 1.3.0.

**Comment by NeverOddOrEven** [comment] 2015-01-08 00:56
So, regarding this I think another issue is that "bower install --config.interactive=false" will fail because it can't auto choose proper dependencies. I reverted the generator to 1.2 until I get it stable (tomorrow? cross fingers) then I plan to find proper bower.json configurations for using angular 1.3 as well as aligning tests where necessary.

**Comment by JuanCaicedo** [comment] 2015-01-09 15:50
I do have a base tag, but I still get the error. However I generated a new
project to test something else and had no problem with the karma tests, so
I think it's been resolved.

**Comment by JuanCaicedo** [comment] 2015-01-09 18:40
Actually it looks like the 0.4-dev generator I just used is now using
angular 1.2, so I think the issue is still around.

On Fri, Jan 9, 2015 at 10:50 AM, Juan Caicedo <retiredcanadianpoet@gmail.com

**Comment by NeverOddOrEven** [comment] 2015-01-10 20:07
@JuanCaicedo Refer to commit: https://github.com/meanjs/generator-meanjs/commit/7f856935121f717c693e9d88e84cfa4d7f478f1e

Closing this issue for now. Plan will be to bump this to 1.3 when we are stable again.

**Closed by NeverOddOrEven** 2015-01-10 20:07 UTC
Labels: discuss, enhancement

**Comment by gadiga** [comment] 2015-02-04 14:43
I am new to Angular and MEAN. But I did develop an app with MEAN. But it would not work with IE 9. So, I just upgraded to AngularJS 1.3 using bower-update and the bootstrap menus stopped working. There is some discussion on this here https://github.com/angular-ui/bootstrap/issues/2914.

**Comment by gadiga** [comment] 2015-02-04 16:19
i found a solution for this as suggested here https://github.com/dalelotts/angular-bootstrap-datetimepicker/issues/126. But IE 9 fails miserably. whatever was working prior to 1.3 upgrade stopped working in IE 9. So, I think I give up on IE :(

**Comment by gadiga** [comment] 2015-02-04 18:10
Uncommenting console.log resolves some issues on IE9, but the original caching problem that 1.3 is supposed to have fixed still exits.

**Comment by gadiga** [comment] 2015-02-04 18:10
sorry I meant commenting console.log

**Comment by gadiga** [comment] 2015-02-04 19:10
Finally made IE9 work with Angular. But I had to write the config code that Angular 1.3 was supposed to fix. But not sure if this tied to the MEAN framework. So this is how I fixed it.
angular.module(<module name>).config(['$httpProvider', function($httpProvider) {
    //initialize get if not there
    if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {};    
    }
    //disable IE ajax request caching
    $httpProvider.defaults.headers.get['If-Modified-Since'] = '0';
}]);

**Comment by wcmetz0** [comment] 2015-03-17 03:06
Hello.  Has there been additional progress on the timeline to upgrade to Angular 1.3?    Thank you to all of the contributors, this is a great framework.

**Comment by SOSANA** [comment] 2015-03-17 03:10
Someone working on the PR for this? There would be two seperate PR's right? one for meanjs-generator and one for core project?

**Comment by JuanCaicedo** [comment] 2015-03-17 14:50
I think I remember someone on the core team saying that the main project is just supposed to be a reflection of the generator-meanjs, so in theory it only needs to get added there. That being said, I'm not sure how they keep them in sync, so you might want to make a PR to generator-means and then reference it in a PR to meanjs.

And last I checked, there was no work on moving to 1.3, so I'm sure they would appreciate the help!

**Comment by RoryOSiochain** [comment] 2015-05-10 16:24
Great work on Mean, just wondering if any decision has been made on this migration? Will Mean be migrating to 1.3 or directly to 1.4? Are there any timelines available? Happy to help out with migration tasks.

**Comment by ilanbiala** [comment] 2015-05-11 00:47
@RoryOSiochain once 0.4 tasks in that milestone are finished we'll work on moving directly to 1.4.

**Comment by abhishekdgeek** [comment] 2017-03-13 13:27
@gadiga is there any other way for doing this? This is not an optimal solution but a good quick fix. Side effect all the requests are processed again and again.
