### ISSUE TITLE
0.4.0 - Running Gulp does not start the server Grunt works fine.

### ISSUE THREAD

**Issue by MangeshMp** [meanjs/mean#364] opened 2015-01-15 05:28 UTC
Running Gulp gives error.
```
[21:21:24] Starting 'nodemon'...
[21:21:24] Finished 'nodemon' after 36 ms
[21:21:24] Starting 'watch'...
[21:21:24] Finished 'watch' after 266 ms
[21:21:24] Finished 'default' after 1.53 s
[21:21:24] Live reload server listening on: 35729
[gulp] [nodemon] v1.3.0-7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: gruntfile.js server.js config/**/*.js modules/*/server/**/*.js
[gulp] [nodemon] starting `grunt server.js`
Warning: Task "server.js" not found. Used --force, continuing.

Done, but with warnings.
[gulp] [nodemon] clean exit - waiting for changes before restart

```

**Comment by Kulver** [comment] 2015-01-15 15:25
Same issue...

**Comment by ilanbiala** [comment] 2015-01-15 16:12
@lirantal @NeverOddOrEven why are we running the `watch` task when `gulp-nodemon` comes with watch support?

**Comment by Kulver** [comment] 2015-01-15 16:26
In package.json change     

 ` "scripts": {
    "start": "grunt",`
to
 ` "scripts": {
    "start": "node",`
and it will work

**Comment by ilanbiala** [comment] 2015-01-16 00:22
@Kulver he is using Gulp as far as I can tell, not `npm start`...

**Comment by Kulver** [comment] 2015-01-16 11:15
@ilanbiala when you run gulp, it launch `gulp nodemon` and if you look at the code of nodemon it runs as
   ` gulp.start.apply(gulp, tasks)`...

**Comment by flipjs** [comment] 2015-01-18 15:52
"scripts": { "start": "node"} in package.json works for me. Thanks.

**Comment by berendt** [comment] 2015-02-16 12:52
I cannot reproduce this issue. I am using `gulp` and the development server is coming up like expected. I tested this with version `0.4-dev`.

```
$ gulp
[...]
Application loaded using the "development" environment configuration

MEAN.JS application started on port 3000
```

**Comment by codydaig** [comment] 2015-07-16 06:48
@Kulver I am unable to reproduce this in 0.4.0 and the current master branch does not have a gulpfile. Is this still an issue or has it been resolved?

**Comment by lirantal** [comment] 2015-07-16 20:10
@codydaig @ilanbiala : this is an old one and I personally don't think we should be spending our effort trying to keep up with both gulp and grunt maintenance. I vote for closing this.

**Comment by ilanbiala** [comment] 2015-07-16 21:29
No, let's just go with Gulp.

**Comment by lirantal** [comment] 2015-07-17 07:52
I don't know who worked on the gulp support for 0.4.0, maybe Amos. I think the gulp settings there are not 100% compatible with the grunt config we have so I suggest we don't invest time on the 0.4.0 release on gulp, and can consider moving to it after we release 0.4.0

Let's create a Roadmap page for 0.5.0 and start stuffing items there.

**Closed by lirantal** 2015-07-17 07:52 UTC
