### ISSUE TITLE
Yo Scaffolding tool - Link broken

### ISSUE THREAD

**Issue by dopeddude** [meanjs/mean#371] opened 2015-01-20 07:43 UTC
Hi,

Not sure if this is the right place to report this issue. 

The "yo scaffolding tool" link on the page "http://meanjs.org/generator.html" under "Getting Started" seems broken.

Thanks.

**Comment by ilanbiala** [comment] 2015-01-24 18:17
Dupe of #270, follow the discussion there.

**Closed by ilanbiala** 2015-01-24 18:17 UTC
Labels: bug
