### ISSUE TITLE
MEAN.js does not work properly in IE10/11.

### ISSUE THREAD

**Issue by wang3g** [meanjs/mean#448] opened 2015-03-05 12:45 UTC
What I did is:
1) download MEAN.js,
2) run 'npm install'
3) run 'grunt'
4) open IE 11
5) input 'localhost:3000', press 'enter'
6) sign up a new user
7) create a new article, and submit
8) click 'Articles->List Articles', the newly added article does not shown!

I then repeated step 4-8 for Chrome and FF. Both worked perfectly. It looks like the problem only exists on IE. I looked into GET /articles request and found that the cookie part is missing in the request header. Please help.

**Comment by ilanbiala** [comment] 2015-03-05 15:11
@wang3g there's no reason it shouldn't work in IE11. Have you disabled cookies/session storage/browser data/enabled "Do not track"?

**Comment by wang3g** [comment] 2015-03-05 23:05
I installed a new IE11 and used default settings. 

I also tried to change Privacy setting to make the IE 'Accept all cookies', but the problem is still there.

**Comment by wang3g** [comment] 2015-03-06 11:14
After I ticked off 'Always send Do Not Track header', it works now. But the default setting for this item in IE 11 is ticked ON. How can we expect ordinary users to know this thing?

**Comment by wang3g** [comment] 2015-03-06 11:48
The weird thing is sometime it works, sometime it does not work in IE11.

**Comment by ilanbiala** [comment] 2015-03-10 00:43
@wang3g when doesn't it work?

**Comment by wang3g** [comment] 2015-03-10 02:15
99% of time, it does not work in IE. I did not change even one line of code. I also tried the IE in another laptop. Same result.

**Comment by ilanbiala** [comment] 2015-03-10 02:50
@wang3g https://www.modern.ie/en-us/screenshots#http%3A%2F%2Fmeanjs.herokuapp.com%2F%23!%2F shows that IE11 renders it properly. What do you see?

**Comment by wang3g** [comment] 2015-03-10 03:32
Most of UIs can be rendered properly in IE. The problem only occurs in the following scenario: 
Step 1) Sign in; 
Step 2) Click  'Articles->New Article', then input some text, then submit.
Step 3) Click  'Articles->List Articles', the newly added article in Step 2 is supposed to be displayed on the screen, but it is not.
Step 4) Click 'Signout', then 'Sign in', then click  'Articles->List Articles', the newly added article is still missing.
Step 5) Close IE browser. Then open a new IE browser, sign in, click  'Articles->List Articles', now the newly added article is on the screen.

**Comment by lirantal** [comment] 2015-08-14 15:13
Still an issue @wang3g ?

**Comment by ilanbiala** [comment] 2015-09-02 19:02
@wang3g closing, if this is still an issue feel free to post with more info and we will revisit.

**Closed by ilanbiala** 2015-09-02 19:02 UTC
Labels: question

**Comment by vencivat** [comment] 2016-11-25 06:36
The problem is with IE caching. Somehow IE wont request json from /articles, and still display the old/cached articles array. Any ideas of how to fix in IE ? IE version 11
