### ISSUE TITLE
Socket Integration for articles

### ISSUE THREAD

**Issue by rohitkumarvinay** [meanjs/mean#1393] opened 2016-07-11 23:43 UTC
I am looking for examples to  integrate socket for articles. 

i tried a method, could not get complete solution. had an issue which i have posted on [stackoverflow](http://stackoverflow.com/questions/38217031/angularjs-meanjs-articles-update-blink-and-reloads-on-socket-emit). please follow that stack link for details.

**Comment by codydaig** [comment] 2016-07-11 23:54
@rohitkumarvinay What do you want to use sockets for with articles?

**Comment by rohitkumarvinay** [comment] 2016-07-12 00:03
@codydaig i want to update and create articles in realtime. i am able to create them seamlessly, but while updating, the data blinks, refreshes and the updated comes again, when the traffic is high, the entire data set keeps on blinking. i am using the repo by @mleanos. this is the [link to repo](https://github.com/mleanos/mean/tree/SocketIO-Config-CRUD)

**Comment by codydaig** [comment] 2016-07-12 00:10
@mleanos Can you speak more to your specific implementation?

**Comment by rohitkumarvinay** [comment] 2016-07-12 00:18
it is a food ordering solution which i am working on, everytime an order(from 'orders' module) has been created from any second computer, the new order created should be pushed to the first computer, which works fine now, but if i update the the same order, the data blinks and comes back up with the updated data on the first computer, when the traffic is high, i.e when the orders are being placed frequently, it keeps on blinking and hence making the data visibility to a very minimal time. i wanted to know if i can seamlessly update data without it blinking. thank for your time

**Comment by codydaig** [comment] 2016-07-12 00:27
@rohitkumarvinay That makes sense. I was asking for @mleanos's input on how he did that implementation in the branch you referenced but your explanation also helps shed more light. 

From the sounds of it though, it seems like the page is updating too frequently. So, I would pout checks in and only update the data on the page that needs updating versus updating all the data.

**Comment by rohitkumarvinay** [comment] 2016-07-12 00:30
Thanks @codydaig, i am also trying on the same, still am unsuccessful.

**Comment by rohitkumarvinay** [comment] 2016-07-27 23:16
@mleanos Please help me solve this issue. thanks

**Comment by mleanos** [comment] 2016-07-27 23:50
@rohitkumarvinay What does your client-side listener for the "orderUpdateSuccess" Socket event look like?

If you're using the exact implementation I have provided, then your problem probably lies with this line: https://github.com/mleanos/mean/blob/SocketIO-Config-CRUD/modules/articles/client/controllers/list-articles.client.controller.js#L34

Anytime an article is updated, the controller will fetch the list of Articles from the server; thus, you will see it as a reload. The Socket event that you're emitting on a successful update is sending the article back to the client. You can find that particular Article in `vm.articles` and update it.

To do this you'll need to find the index & then set that array element to the updated Article returned from the Socket event.

**Comment by rohitkumarvinay** [comment] 2016-07-27 23:59
@mleanos  i am using the exact implementation you provided. I tried different solutions, proved in-effective. could you tell me how exactly i can proceed to do so. thanks

**Comment by mleanos** [comment] 2016-07-28 00:15
In your Orders list client controller, you should have `vm.orders` in scope. You should also have a listener registered with the SocketIO client for your "orderUpdateSuccess" event that's emitted from the Socket server config routine.

In your "orderUpdateSuccess" listener (client-side) you need to search `vm.orders` to find the index of the Order that has been updated. If you find the index, then do something like `vm.orders[indexOfUpdatedOrder] = order`; `order` being the data sent from the Socket server event to your listener. My example is sending this data back too, so you should be using it in your listener signature.

If you don't find the Order for some reason, then you can just add it to `vm.orders` using `unshift`, just like you're probably doing when a new Order is added.

This should be enough info for you to solve this issue; I can update my branch to use this methodology but I probably won't get to it anytime soon. If you need further assistance, message me on Gitter & I'll be more than happy to go over it with you. However, please try to solve this yourself with the guidance that I gave here.

My SocketIO-Config-CRUD branch was meant as an example & to be mere starting point; that's why this limitation was not fully thought out. Feel free to submit a PR to that branch if you'd like to contribute, and when similar issues arise it might be more appropriate to open on issue with the fork that it specifically pertains to; since this issue isn't relevant to the MEANJS framework.

**Comment by rohitkumarvinay** [comment] 2016-07-28 00:17
@mleanos  i tried the same method you had followed for `orderCreateSuccess`, it works. i used the below inside `orderUpdateSuccess`
```
if ($scope.orders) {
        $scope.orders.unshift(response.data);
      }
```

**Comment by mleanos** [comment] 2016-07-28 00:20
Does this add a new instance of the Order to your list? Or does it update the existing Order? From my understanding of the `unshift` method, it would add a new instance & now you would have duplicate Orders in your list.

**Comment by rohitkumarvinay** [comment] 2016-07-28 00:23
No there are no duplicates, it updates the existing order.

**Comment by mleanos** [comment] 2016-07-28 00:28
You might want to verify that is the case. I don't see how that's possible with the `unshift` method.

I'm closing this issue since it appears that the cause of your issue has been identified. But feel free to continue the discussion here.

**Closed by mleanos** 2016-07-28 00:28 UTC
Labels: feedback:question, Not Mean.JS Specific

**Comment by mleanos** [comment] 2016-07-28 00:30
Another point about the `unshift`.. try updating an Order that is on the top of the list your viewing. This should illustrate my point.

**Comment by rohitkumarvinay** [comment] 2016-07-28 00:38
i have been updating the order on top of my list, also i tried creating a new Order and updating that as well, seems to work fine, if i come up with issues, will update it here. Thanks again
