### ISSUE TITLE
jshint task fails when invoking `grunt`

### ISSUE THREAD

**Issue by andrewsomething** [meanjs/mean#882] opened 2015-09-03 18:50 UTC
Checking out the v0.4.1 tag and running `grunt` fails with:

```
Running "jshint:all" (jshint) task

   modules/articles/server/policies/articles.server.policy.js
      9 |acl = new acl(new acl.memoryBackend());
                   ^ A constructor name should start with an uppercase letter.
   modules/users/server/policies/admin.server.policy.js
      9 |acl = new acl(new acl.memoryBackend());
                   ^ A constructor name should start with an uppercase letter.

>> 2 errors in 102 files
Warning: Task "jshint:all" failed. Use --force to continue.
```

node version: v0.12.7
gulp-jshint version: 1.11.2
grunt-contrib-jshint version: 1.11.2 

Adding `/*jshint -W055 */` to the line above will force jshint to ignore the issue.

**Comment by mleanos** [comment] 2015-09-03 19:45
I've confirmed this is happening in the master branch as well. I can't be sure of the cause but this is the behavior that I experienced with this...

I pulled down the most recent *master* branch, and ran `grunt`. The `jshint` succeeded fine. I then pulled down the 0.4.1 tag version, into a separate project, & ran `grunt`. The `jshint` failed with the above errors.

Finally, I cleared my node_modules from my local *master* branch & re-installed the packages. Ran `grunt`, and the `jshint` failed with the above errors. This tells me that it's something with a dependency; perhaps `grunt-contrib-jshint`. However, it's difficult to determine what package might be causing this behavior. 

Adding the following line to `

**Comment by italiancollectiveco** [comment] 2015-09-03 20:45
Same error here. And above solution worked for me also.

**Comment by hectorleiva** [comment] 2015-09-03 20:53
^ I did the same and it also worked.

**Comment by mleanos** [comment] 2015-09-03 21:41
A more appropriate solution might be to use `/*jshint -W055 */` as @andrewsomething suggested, since technically the `newcap` option is deprecated.

**Comment by italiancollectiveco** [comment] 2015-09-03 21:55
@mleanos I am not sure how to implement @andrewsomething solution. Adding /*jshint -W055 */ to which files?

Thank you

**Comment by mleanos** [comment] 2015-09-03 21:57
@italiancollectiveco See #883 I just updated the solution in favor of @andrewsomething suggestion.

**Comment by mleanos** [comment] 2015-09-03 22:01
@italiancollectiveco @hectorleiva @andrewsomething  Perhaps add a comment to #833 if it fixes the issue for you, so we can get this merged quickly.

**Comment by mleanos** [comment] 2015-09-04 00:59
A patch has been released by `grunt-contrib-jshint` for this https://github.com/gruntjs/grunt-contrib-jshint/commit/730434875b15d79970b736aadac246cfc400bfe4

**Comment by lirantal** [comment] 2015-09-04 13:41
Issue has already been solved by upstream as @mleanos updated

**Closed by lirantal** 2015-09-04 13:41 UTC
Labels: bug
