### ISSUE TITLE
Need to add data-toggle="dropwdown" to Menu generator after upgrading angular-ui bootstrap

### ISSUE THREAD

**Issue by christopherdro** [meanjs/mean#495] opened 2015-03-26 06:37 UTC
After resolving this issue https://github.com/angular-ui/bootstrap/issues/2868, I had to manually add data-toggle="dropdown" to the bootstrap nav element so that the dropdown would show properly.

Maybe the fact that it was missing is what was causing the error in the first place?
Looks like it's already in place for the profile dropdown, just not in the data-ng-repeat that generates the Menus.

Hope it helps.

**Comment by ilanbiala** [comment] 2015-03-26 10:30
Sounds like this is a dupe of https://github.com/meanjs/mean/issues/365, no?

**Comment by christopherdro** [comment] 2015-03-26 14:11
Yup. Thanks

**Closed** 2015-03-27 02:38 UTC
Labels: bug, duplicate
