### ISSUE TITLE
about admin control center

### ISSUE THREAD

**Issue by ChenYongFang** [meanjs/mean#128] opened 2014-08-04 09:09 UTC
I see that the project currently haven't a admin control module , and I want to implement , but we are using SPA angularjs application , so when I need the admin control center pages style different then front pages there are tow problem needs to solve.

one : if is a SPA , the index can't have any other view , then we need use localhost/#!/home/(other pages) and the admin path would look like this localhost/#!/admin/(other pages) so , here's the problem every front page need the common stuff , must be home state's child.

two : we let the application have tow access point , but this means we have to generate localhost/admin/#!/ the admin page and deal with new admin module , but meanjs is auto add asset . and I want when access to admin , other module don't auto load . I don't really know what's the best way to do.   I really need this , thanks.

**Comment by codydaig** [comment] 2015-07-23 19:30
Duplicate of #41 ?

**Comment by lirantal** [comment] 2015-07-24 10:43
Indeed, let's close.

**Closed by lirantal** 2015-07-24 10:43 UTC
Labels: enhancement, modules
